### ISSUE TITLE
save config

### ISSUE THREAD

**Issue by dries-c** [AndreTheGamer/SurvivalGame#10]
[CRITICAL]: Could not save Config /Users/Ronny/Desktop/Catching Fire/plugins/SurvivalGame/config.yml: file_put_contents(/Users/Ronny/Desktop/Catching Fire/plugins/SurvivalGame/config.yml): failed to open stream: No such file or directory

**Comment by xZeroMCPE** [comment]
Make a folder in you're plugin folder called: SurvivalGame  then restart server and it should save the config :)

**Comment by dries-c** [comment]
It work in my version

Dries C
Op 22-dec.-2015 19:17 schreef "Andre" notifications@github.com:

**Comment by dries-c** [comment]
I have fix it in my fork

**Comment by xZeroMCPE** [comment]
Yea, just download the latest .PHAR from the readme.md and add to you're server plugin folder and then create a folder in plugin folder called SurvivalGame and restart server then it should save the config. :+1:

**Comment by dries-c** [comment]
but my version save automatic the resources

**Comment by xZeroMCPE** [comment]
Oh, ok what line did you added? Create a pull request on my version that's fix the auto saving.
