### ISSUE TITLE
Why not support language Chinese.

### ISSUE THREAD

**Issue by PoilZero** [AndreTheGamer/SurvivalGame#100]
Why not support language Chinese.
We are very huge.

**Comment by xZeroMCPE** [comment]
We do, we just need someone that's willing to translate it

**Comment by ghost** [comment]
I'll try to do it :smile:

**Comment by xZeroMCPE** [comment]
@ankitmaharjan252  ok

**Comment by ghost** [comment]
@ibookcc Added Test it!

**Comment by PoilZero** [comment]
@ankitmaharjan252 Chest_Refilled is not truth. should be 箱子已重置

**Comment by ghost** [comment]
Just translated it with Google Translator. So something might get wrong. 
Its fixed!
Anything wrong? Tell me and i'll fix it

**Comment by PoilZero** [comment]
@ankitmaharjan252 have not find others.

**Comment by ghost** [comment]
ok :smile:
