### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by JackDiSpade21** [AndreTheGamer/SurvivalGame#102]
Hello, in my server when I try to load the Plugin it crashes.
## Here the crash dump: 

Genisys Crash Dump Wed Sep 28 21:26:40 CEST 2016

Error: syntax error, unexpected 'Seems' (T_STRING), expecting ',' or ')'
File: /SurvivalGames.phar/src/Andre/SurvivalGames/Main
Line: 279
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[270]       }else{
[271]           $sender->sendMessage(TextFormat::RED . "That command can only be used in-game!");
[272]           return true;  
[273]       }
[274]               break; 
[275]       case "set":
[276]       if($sender instanceof Player){
[277]           if($this->config->exists("lastpos"))
[278]           {
[279]               $sender->sendMessage("TextFormat::BLUE . "Seems like you have already setup an arena");
[280]           }
[281]           else
[282]           {
[283]               $name=$sender->getName();
[284]               $this->SetStatus[$name]=0;
[285]               $sender->sendMessage("Tap a sign to set it as join sign!");
[286]           }
[287]       }else{
[288]           $sender->sendMessage(TextFormat::RED . "You may only use ths command in-game!");
[289]           return true;        

Backtrace:
#0 (): spl_autoload_call(string Andre\SurvivalGames\Main)
#1 /src/pocketmine/plugin/PharPluginLoader(64): class_exists(string Andre\SurvivalGames\Main, boolean 1)
#2 /src/pocketmine/plugin/PluginManager(152): pocketmine\plugin\PharPluginLoader->loadPlugin(string phar:///home/gs/gs/data/servers/2802461/plugins/SurvivalGames.phar)
#3 /src/pocketmine/plugin/PluginManager(330): pocketmine\plugin\PluginManager->loadPlugin(string /home/gs/gs/data/servers/2802461/plugins/SurvivalGames.phar, array Array())
#4 /src/pocketmine/Server(1909): pocketmine\plugin\PluginManager->loadPlugins(string /home/gs/gs/data/servers/2802461/plugins/)
#5 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gs/gs/data/servers/2802461/genisys-latest.phar/, string /home/gs/gs/data/servers/2802461/, string /home/gs/gs/data/servers/2802461/plugins/, string unknown)
#6 (1): require_once(string phar:///home/gs/gs/data/servers/2802461/genisys-latest.phar/src/pocketmine/PocketMine.php)

Genisys version: a85f8786040d59f44414d025090bf3c58432296f [Protocol 83; API 2.0.0]
uname -a: Linux fr42.server.pro 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 0 seconds
Number of loaded worlds: 0
Players online: 0/10

Loaded plugins:
VPNGuard 1.0.5 by basprohop for API(s) 1.13.0, 2.0.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
WorldEdit+ 0.01 by  for API(s) 2.0.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
SubSigns 1 by Samueljh1 for API(s) 1.0.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
TestPlugin 1.0.0 by  for API(s) 1.0.0
ServerLoveMCPE 3.2.1 by TheDeibo, ratchetgame98, and, The Plugin Community! for API(s) 2.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.0.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
TNTRun 1 by DavidJBrockway aka MCPE_PluginDev for API(s) 2.0.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
TimeCommander 2.1 by LDX for API(s) 1.0.0, 2.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.7 by onebone for API(s) 1.12.0
ManyWorlds 2.2.0dev1 by aliuly for API(s) 2.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
iControlU 1.3 by Falkirks for API(s) 1.6.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
CapsLimit 1.0.0 by deot for API(s) 1.12.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0

**Comment by xZeroMCPE** [comment]
Should be good now! 

Download a new zip file

**Comment by JackDiSpade21** [comment]
Another thing, if I want to make all maps only 8 slots?

**Comment by xZeroMCPE** [comment]
Wait till the new update comes, it"ll allow you to set how many slots a arena can have etc!

**Comment by JackDiSpade21** [comment]
Okay thanks, you can close if you want. You're a fantastic developer!
