### ISSUE TITLE
Warnings and errors 

### ISSUE THREAD

**Issue by Xelcronia** [AndreTheGamer/SurvivalGame#103]
Plugin  on load : 

Warning: mkdir(): Permission denied in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 65

Warning: file_put_contents(/home/xel/plugins/SurvivalGames/Language/Message-eng.yml): failed to open stream: No such file or directory in phar:///home/xel/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 207
[07:59:23] [Server thread/INFO]:
 *
 *
-  _____                  _            _  _____
  / ____|                (_)          | |/ ____|
  | (___  _   _ _ ____   _____   ____ _| | |  __  __ _ _ __ ___   ___  ___
  ___ | | | | '**\ \ / / \ \ / / _` | | | |_ |/ _` | '_ ` _ \ / _ \/ __|
  __**) | |_| | |   \ V /| |\ V / (_| | | |**| | (_| | | | | | |  __/\** \
  |_____/ __,_|_|    \_/ |_| \_/ __,_|_|_____|__,_|_| |_| |_|___||___/
  *
- GitHub: GitHub.com/xZeroMCPE/SurvivalGames
- Using version: 1.0.10

_On joining a game_
Notice: Undefined variable: Time in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 584
[08:09:51] [Server thread/INFO]: [SurvivalGames]  2:30.                                               [08:10:08] [Server thread/INFO]: <Xelcronia> i dont see you

Notice: Undefined variable: Force_Start in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 324                                           [08:10:15] [Server thread/INFO]:                                                                      [08:10:15] [Server thread/INFO]: <Max> i see u

Notice: Undefined variable: Starting in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 563                                              [08:10:15] [Server thread/INFO]:  4 seconds  
Notice: Undefined variable: Starting in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 560                                              [08:10:16] [Server thread/INFO]:  3 seconds

Notice: Undefined variable: Starting in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 557                                              [08:10:17] [Server thread/INFO]:  2 seconds
Notice: Undefined variable: Starting in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 554                                              [08:10:18] [Server thread/INFO]:  1 seconds
Notice: Undefined variable: Started in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 589                                               [08:10:19] [Server thread/INFO]:  
Notice: Undefined variable: p in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 591
[08:10:19] [Server thread/CRITICAL]: Could not execute task pocketmine\scheduler\CallbackTask: Call to a member function hasPermission() on unknown
[08:10:19] [Server thread/CRITICAL]: Error: "Call to a member function hasPermission() on unknown" (EXCEPTION) in "/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main" at line 591

Notice: Undefined variable: Chest_Refilled in phar:///home/xel/plugins/phar_SurvivalGames-master-5_RxAtknIA7KnLMVj.phar/src/Andre/SurvivalGames/Main.php on line 615

**Comment by Xelcronia** [comment]
Also when the game starts, the players remain invincible. :(

**Comment by xZeroMCPE** [comment]
I"ll get this fixed soon!

**Comment by Xelcronia** [comment]
Okay :D

**Comment by ghost** [comment]
Is this fixed?

**Comment by ghost** [comment]
Reopen if this still exist
