### ISSUE TITLE
ChestRefill?

### ISSUE THREAD

**Issue by SinlesFlyer376** [AndreTheGamer/SurvivalGame#104]
How do I do the chest config thing

**Comment by xZeroMCPE** [comment]
Will be adding chest refill soon :)

**Comment by SinlesFlyer376** [comment]
Can you make it to where you can fill the chests with random things and addwhst things we want in each chest and we can put a percentage of things in thechest like iron armor (You dont want a full chest full of iron armor you want it to have like apples a piece of iron armor and maybe sword)

**Comment by xZeroMCPE** [comment]
Yeah

**Comment by SinlesFlyer376** [comment]
How about the chests always refill randomly at the end of a match each time

**Comment by SinlesFlyer376** [comment]
I am the person you talk to everyday btw on Skype (Tyler Chaky)
