### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by GoldCodes** [AndreTheGamer/SurvivalGame#106]
Can you please update the api?

**Comment by xZeroMCPE** [comment]
Should be.

**Comment by GoldCodes** [comment]
@xZeroMCPE It says incompatiple api version with php7 and 16.3

**Comment by GoldCodes** [comment]
@xZeroMCPE Can you release it?? I need the new api version Thank You!

**Comment by xZeroMCPE** [comment]
Which server software are you using?

**Comment by ghost** [comment]
I've bumped the api so it should work now!

**Comment by GoldCodes** [comment]
Log:
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [21:09:50] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [21:09:50] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [21:09:50] [Server thread/INFO]: Loading server properties...
[Server] [21:09:50] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [21:09:50] [Server thread/INFO]: Starting Minecraft: PE server version v0.16.0.5 alpha
[Server] [21:09:50] [Server thread/INFO]: Starting remote control listener
[Server] [21:09:50] [Server thread/INFO]: RCON running on 0.0.0.0:19132
[Server] [21:09:50] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [21:09:50] [Server thread/INFO]: This server is running PocketMine-MP version 1.6.1dev "Unleashed" (API 2.1.0)
[Server] [21:09:50] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [21:09:51] [Server thread/INFO]: Loading recipes...
[Server] [21:09:51] [Server thread/ERROR]: Could not load plugin 'EconomyAPI': Incompatible API version
[Server] [21:09:51] [Server thread/ERROR]: Could not load plugin 'SurvivalGames': Incompatible API version
[Server] [21:09:52] [Server thread/INFO]: Loading EssentialsPE v2.0.0
[Server] [21:09:52] [Server thread/INFO]: Loading Slapper v1.2.9.7
[Server] [21:09:52] [Server thread/INFO]: Loading MagicWE v0.2.7
[Server] [21:09:52] [Server thread/INFO]: [MagicWE] MagicWE has been loaded!

**Comment by ghost** [comment]
You downloaded that from releases page which is outdated!
Download the DevTools and the source (not from release) and copy source to plugins folder! Start the server

**Comment by GoldCodes** [comment]
Where do I get Dev tools?

**Comment by ghost** [comment]
Cause you need to load source code of this plugin.

**Comment by GoldCodes** [comment]
Thx!

**Comment by GoldCodes** [comment]
leave it in the folder?

**Comment by ghost** [comment]
Download the src and copy the folder into plugins folder!
