### ISSUE TITLE
Ive tried messing around with some stuff but I cant get it to work

### ISSUE THREAD

**Issue by GoldCodes** [AndreTheGamer/SurvivalGame#108]
![screenshot 2016-12-03 at 9 53 45 pm](https://cloud.githubusercontent.com/assets/22961192/20863752/8f256e60-b9a3-11e6-921a-f76ddac3a4a6.png)
![screenshot 2016-12-03 at 9 56 49 pm](https://cloud.githubusercontent.com/assets/22961192/20863751/8f256604-b9a3-11e6-88af-528e8e73a071.png)

**Comment by xZeroMCPE** [comment]
Just add the missing class on the "use" statement.

**Comment by ghost** [comment]
I think PocketMine and other spoon doesn't support CallBackTask anymore. So, to fix this you should create a new file on the plugin called CallBackTask.php and add the main callbacktask from the older version!..

**Comment by GoldCodes** [comment]
![screenshot 2016-12-04 at 10 12 16 am](https://cloud.githubusercontent.com/assets/22961192/20867097/8a9ad382-ba0a-11e6-914d-99f43dda4a66.png)

**Comment by xZeroMCPE** [comment]
@ankitmaharjan252 Can you confirm / test this and commit.

Thanks!

**Comment by GoldCodes** [comment]
Note: That Does NOT work

**Comment by GoldCodes** [comment]
Im going to look into rewriting that part

**Comment by GoldCodes** [comment]
We may need to make a total remake of this plugin -_-

**Comment by xZeroMCPE** [comment]
lol

**Comment by ankitmaharjan252** [comment]
xD I'm test my idea out!

**Comment by ghost** [comment]
Added like i said on another issue download the latest source and run! It should work now!

**Comment by GoldCodes** [comment]
https://github.com/PluginMine. Ive tried this it works?

**Comment by GoldCodes** [comment]
@ankitmaharjan252 It is giving the same error.

**Comment by GoldCodes** [comment]
We need to rewrite this plugin in different files and bring them in all in one.... look at onebones economyapi

**Comment by xZeroMCPE** [comment]
Maybe, work on background through different branch or local, and well assist!

**Comment by GoldCodes** [comment]
@xZeroMCPE [Join](https://github.com/PluginMine)

**Comment by xZeroMCPE** [comment]
Okay..

**Comment by ghost** [comment]
You invited me as well... Anyways Joined!!
