### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by kabluinc** [AndreTheGamer/SurvivalGame#110]
[Server] [16:42:17] [Server thread/CRITICAL]: ClassNotFoundException: "Class Andre\SurvivalGames\Task not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[Server] [16:42:17] [Server thread/INFO]: Disabling SurvivalGames v1.0.9

**Comment by GoldCodes** [comment]
I am working on this issue. I think I have solved the issue

**Comment by ghost** [comment]
This has been fixed on the latest commit
