### ISSUE TITLE
Configurable player count

### ISSUE THREAD

**Issue by MHIGists** [AndreTheGamer/SurvivalGame#112]
Sorry to post as an issue but can you make the player count for each arena to be set trough command because there is Multi-Arena system and it kinda bad to not be able to chose how many people an arena can have.Like if I want to create 2 vs 2 or 5 vs 5.I can't so please make it possible.I tried to make it myself but sadly I'm not that skilled as you are

**Comment by xZeroMCPE** [comment]
When the system finishes, i plan on adding that.

**Comment by MHIGists** [comment]
This would be sooo awesome thnx man!

**Comment by ghost** [comment]
this plugin work with BlueLight to

**Comment by xZeroMCPE** [comment]
https://github.com/xZeroMCPE/SurvivalGames/issues/118
