### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XDqrkneZ** [AndreTheGamer/SurvivalGame#115]
19:34:47 [CRITICAL] Could not save Config /root/test/plugins/SurvivalGames/Language/Message-eng.yml: file_put_contents(/root/test/plugins/SurvivalGames/Language/Message-eng.yml): failed to open stream: No such file or directory
19:34:47 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\Server::getLevelByName() must be of the type string, null given, called in /root/test/plugins/SurvivalGames-master/src/Andre/SurvivalGames/Main.php on line 115" (EXCEPTION) in "/src/pocketmine/Server" at line 1028

**Comment by xZeroMCPE** [comment]
World loaded?

And this plugin is outdated. I'm planning on rewriting it on my free time.

**Comment by XDqrkneZ** [comment]
@xzeromcpe the error showed on server startup

**Comment by xZeroMCPE** [comment]
The first error is nothing more. The second one was an easy fix, so I fixed it. It should load the level automatically. 

But please keep in mind that I plan to completely rewrite this entire plugin on my free time. But anyhow, enjoy the current version.

**Comment by XDqrkneZ** [comment]
thanks @xZeroMCPE <3
