### ISSUE TITLE
How do I install this on my Pocketmine-MP (mac) server?

### ISSUE THREAD

**Issue by ZeroToil-Network** [AndreTheGamer/SurvivalGame#117]
How am I suppose to install this on my MCPE (PocketMine MP server?)

**Comment by xZeroMCPE** [comment]
same as any plugin

**Comment by ZeroToil-Network** [comment]
It doesn't work for me.

**Comment by ZeroToil-Network** [comment]
It says this when I run my PocketMIne server: 

Warning: mkdir(): Permission denied in /Users/admin/Desktop/server/MCPE/plugins/SurvivalGames-master/src/Andre/SurvivalGames/Main.php on line 64

Warning: file_put_contents(/Users/admin/Desktop/server/MCPE/plugins/SurvivalGames/Language/Message-eng.yml): failed to open stream: No such file or directory in phar:///Users/admin/Desktop/server/MCPE/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 206
[19:14:32] [Server thread/CRITICAL]: pocketmine\level\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1083
