### ISSUE TITLE
dont save level

### ISSUE THREAD

**Issue by dries-c** [AndreTheGamer/SurvivalGame#19]
i have found the problem if you after setup play it work
but if you restart and play than this : Could not execute task pocketmine\scheduler\CallbackTask: Undefined property: Andre\SurvivalGame\Main::$level
[06:45:36] [NOTICE]: UndefinedPropertyException: "Undefined property: Andre\SurvivalGame\Main::$level" (E_NOTICE) in "/plugins/SurvivalGames-master/src/Andre/SurvivalGame/Main" at line 437

he dont save level in the points.yml

**Comment by xZeroMCPE** [comment]
That's the main issue most player are having.  I don't get that issue you just have to make sure the arena/sign is setup on the same world togethere.

**Comment by dries-c** [comment]
Yes on the same world
But i use imagicalmine a fork from pocketmine i think that is the problem

Dries C
Op 24-dec.-2015 17:03 schreef "Andre" notifications@github.com:

**Comment by xZeroMCPE** [comment]
Yea

**Comment by Taki21** [comment]
undefined $level -> #23

**Comment by xZeroMCPE** [comment]
Thanks, got it!

**Comment by xZeroMCPE** [comment]
Its fix.
