### ISSUE TITLE
Doesnt tp player to the level or even start the game

### ISSUE THREAD

**Issue by EpicArtz08999** [AndreTheGamer/SurvivalGame#21]
in console saids this :

26.12 20:14:03 [Server] Server thread/NOTICE UndefinedVariableException: "Undefined variable: event" (E_NOTICE) in "/SurvivalGame_v1.0.5.phar/src/Andre/SurvivalGame/Main" at line 175
26.12 20:14:03 [Server] Server thread/CRITICAL Unhandled exception executing command 'lobby' in lobby: Undefined variable: event
26.12 20:14:02 [Server] Server thread/NOTICE UndefinedPropertyException: "Undefined property: Andre\SurvivalGame\Main::$level" (E_NOTICE) in "/SurvivalGame_v1.0.5.phar/src/Andre/SurvivalGame/Main" at line 486
26.12 20:14:02 [Server] Server thread/CRITICAL Could not execute task pocketmine\scheduler\CallbackTask: Undefined property: Andre\SurvivalGame\Main::$level
26.12 20:14:01 [Server] Server thread/NOTICE UndefinedPropertyException: "Undefined property: Andre\SurvivalGame\Main::$level" (E_NOTICE) in "/SurvivalGame_v1.0.5.phar/src/Andre/SurvivalGame/Main" at line 486
26.12 20:14:01 [Server] Server thread/CRITICAL Could not execute task pocketmine\scheduler\CallbackTask: Undefined property: Andre\SurvivalGame\Main::$level
26.12 20:14:00 [Server] Server thread/NOTICE UndefinedPropertyException: "Undefined property: Andre\SurvivalGame\Main::$level" (E_NOTICE) in "/SurvivalGame_v1.0.5.phar/src/Andre/SurvivalGame/Main" at line 486

**Comment by xZeroMCPE** [comment]
Hi, delete the whole "SurvivalGame" folder then restart server and set up the arena again then try to join arena. " Do Not Restart". Cause whenever you restart the server and try to join again it will not work. You must set arena again and join without restarting server. I will try to fix this bug and when it's fix you will be able to join the arena after restart. Thanks /

**Comment by EpicArtz08999** [comment]
lol ok i guess i will wait

**Comment by EpicArtz08999** [comment]
and thx for your work

**Comment by xZeroMCPE** [comment]
Sure, no problem :)

**Comment by Taki21** [comment]
Fixed Error

**Comment by xZeroMCPE** [comment]
Got it!

**Comment by EpicArtz08999** [comment]
and here comes another one 

Fatal error: Cannot use object of type pocketmine\math\Vector3 as array in C:\Users\Blenda\Downloads\PocketMine-MP\plugins\SurvivalGame-master\src\Andre\SurvivalGame\Main.php on line 1091

Call Stack:
    0.0351     447520   1. {main}() C:\Users\Blenda\Downloads\PocketMine-MP\PocketMine-MP.phar:0
    0.0389     442424   2. require('phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\Blenda\Downloads\PocketMine-MP\PocketMine-MP.phar:1
    2.2223     582976   3. pocketmine\Server->__construct() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:466
    9.3641   26599832   4. pocketmine\Server->start() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1701
    9.4520   26700624   5. pocketmine\Server->tickProcessor() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2100
   75.0021   61101856   6. pocketmine\Server->tick() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2222
   75.0022   61101920   7. pocketmine\network\Network->processInterfaces() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2470
   75.0022   61101920   8. pocketmine\network\RakLibInterface->process() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/Network__32bit.php:160
   75.0029   61101952   9. raklib\server\ServerHandler->handlePacket() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/RakLibInterface.php:81
   75.0030   61102928  10. pocketmine\network\RakLibInterface->handleEncapsulated() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/raklib/server/ServerHandler__32bit.php:90
   75.0033   61103800  11. pocketmine\Player->handleDataPacket() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/RakLibInterface.php:140
   75.0036   61104120  12. pocketmine\level\Level->useItemOn() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player__32bit.php:1980
   75.0038   61104896  13. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/level/Level__32bit.php:1669
   75.0067   61104896  14. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:673
   75.0067   61104896  15. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
   75.0067   61104896  16. Andre\SurvivalGame\Main->playerBlockTouch() phar://C:/Users/Blenda/Downloads/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36

**Comment by dries-c** [comment]
Wow

**Comment by dries-c** [comment]
Version from pocketmine

**Comment by Taki21** [comment]
xD ill fix it

**Comment by AndreTheGamer** [comment]
It has been fix be me. Go head and and try it again, and it should work.

**Comment by xZeroMCPE** [comment]
It's fixed. Download the new release via out main GitHub page ;)
