### ISSUE TITLE
Crash Set Arena

### ISSUE THREAD

**Issue by ghost** [AndreTheGamer/SurvivalGame#24]
ImagicalMine Crash Dump Wed Dec 30 14:03:30 GMT 2015

Error: Cannot use object of type pocketmine\math\Vector3 as array
File: /SG.phar/src/Andre/SurvivalGame/Main
Line: 1091
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SurvivalGame v1.0.1

Code:
[1082]                      "x" =>$block->x,
[1083]                      "y" =>$block->y,
[1084]                      "z" =>$block->z,
[1085]                      "level" =>$levelname);
[1086]                  $this->config->set("pos24",$this->pos24);
[1087]                  $this->config->save();
[1088]                  $this->SetStatus[$username]++;  
[1089]              $player->sendMessage(TextFormat::GREEN."Spawnpoint 24 created!");
[1090]                  $player->sendMessage(TextFormat::GREEN."Please click on the deathmatch location");  
[1091]                  $this->pos23=new Vector3($this->pos23["x"]+0.5,$this->pos23["y"],$this->pos23["z"]+0.5);
[1092]                  break;  
[1093]          case 25:
[1094]          $this->lastpos=array(
[1095]                  "x" =>$block->x,
[1096]                  "y" =>$block->y,
[1097]                  "z" =>$block->z,
[1098]                  "level" =>$levelname);
[1099]              $this->config->set("lastpos",$this->lastpos);
[1100]              $this->config->save();
[1101]              unset($this->SetStatus[$username]);

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/plugin/MethodEventExecutor(41): Andre\SurvivalGame\Main->playerBlockTouch(boolean)
#2 /src/pocketmine/plugin/RegisteredListener(101): pocketmine\plugin\MethodEventExecutor->execute(boolean)
#3 /src/pocketmine/plugin/PluginManager(678): pocketmine\plugin\RegisteredListener->callEvent(boolean)
#4 /src/pocketmine/level/Level(1797): pocketmine\plugin\PluginManager->callEvent(boolean)
#5 /src/pocketmine/Player(2090): pocketmine\level\Level->useItemOn(boolean)
#6 /src/pocketmine/network/RakLibInterface(145): pocketmine\Player->handleDataPacket(boolean)
#7 /src/raklib/server/ServerHandler(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#8 /src/pocketmine/network/RakLibInterface(86): raklib\server\ServerHandler->handlePacket(boolean)
#9 /src/pocketmine/network/Network(165): pocketmine\network\RakLibInterface->process(boolean)
#10 /src/pocketmine/Server(2509): pocketmine\network\Network->processInterfaces(boolean)
#11 /src/pocketmine/Server(2243): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server(2121): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server(1722): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(boolean)
#15 (1): (boolean)
#16 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.13.2]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT BULUT 6.2 build 9200 (Windows 8 Home Premium Edition) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SurvivalGame 1.0.1 by AndreTheGamer for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvmT00iW/ldyDBFjti3b8lW2iSKCgWqaCKA8VDFsLCaIlJSy1aWrlVK5TAf/+37vZUqWXVVs
x+z+sMyBlce78ntXJn92yihRnaU7mbqT+WTkDnsdVRRZ0Vn+2Sn3OaY6F98uPn68/NjpdRKltdzQ
2CuZplkpKq1E5v2u/FJkoaD1Is/8G1UmUarW60SW2/X6X5jOirGQWsiikHsQCqOYqAyu3vTzrSwG
uvAHL9OgUIOrqriNbmX8RiZq8F5GKVbHIAYRhwv3R6+Tx9UGo8tOeyUW+VmgSGh3OB9hVqzL5j+d
u3VHnL946sWQzXlx18NyLBufLtsfLdvbZZPTZd+Pln23y6any2J1q2KzlH+mkPPZc7N41l78tNxG
2nnhZ2kYbZwXWpXddSfP9Giy7vTsJH/Wu89+tlveqm69cP7AwitVXpWyrPSXpzi9gqT6+ssvz2mF
2bTApmZPHsu9KkioNHhvTr97re7KX7MCh7tcvvl4cfGhv+5c5XKX5lmUlmI0EX6hZKmCv607VpLF
8EiSv0p1FSsJhPlx5N+ILBXlVokApLdY5W8FDkCWUZYSm5q2Yec+oDiZcHyeqp2wgOy2J74wSr7+
MuxPeyfjgMXX07Hvdm2t3xHkPKh/c7DoYtxY1Cd1RtOlGZ8045Z6LHUJDufsJl2zaNo6jkexvJid
rHoQyouzk1UPInkxP1n1EyAvjsDyEI6tSgck2wFDwB0Of0LgAGV36LbWVSnR/gmesQmRoiykj5Dw
pfNkKDjCHELT4EoVt6roDp8tjwKWGYYIhdTb11WSd70sAwjTZ5DiiXuPjAlGg/eq3GbBxa1Ky4s7
5VdAV3figjbHNJBthar1mqIakMQ+8A8y/XVW+dsjTqPHOH1Um0iXqlDBO/o7hQ6wzYkWZi0Y3RfL
eaH4lzpiN36M3Yr/ei9TeGjRnZ3NH+F0XyzYUMYx8z5iNbnHijE1eEf/33XPFmePsDgS5THq03vU
V2zm7ggh6ISwgfWaGTsvgJ23pUou0yN6s3v0UlXusuJm8FHevIu8tymUDgGzLhLoCf2VDXJbmQax
ei1LuZI0e8TgzDAo5E0ceQPN8LPg/I33Fd17glsRYPVjGWpWF6kvc13FFIKPmM3/sjbzGXgaodZr
I1XtHFasmtkDOi0eZfPB/N11Z9O/rFNeZD5SxLEjPurQo+lw8Rhpy70h2TA5Ie4+Snw0GT8SMEpk
qGMqo0epuCP3J1RWRjhEkCNy48fIuWej0SPkdCmL46Nx77vfin++x8/uZLZ4hNK3bwjKuiwq/4Te
VHRJmePBmeDA+meCQPfjMPW119lQaJAx1Wmgq5G7Edbd/jBQt9jpVVEcdJYoQXFCZeZnWDie9zoy
j3iZO+6PsGwTlfgc/sU/2GCATHv6Z30aqChL4PtzlAbZTosP1+Ifn959uhaz/kiwFGIxGg5Ft14w
F79liRKrQiVRlYiLIKK645mIpijlIO42B7Vpf9anr++oavA5wufQTH7LNHF7++HDNQb4Y4catqlm
NRnkAibOkv3L1Vv6shK2Bnstk436w/4CI7JChC80JbksVR7+R1Zme30hu7IAMJz9e9T87fLfY/s9
tt8T+z3BN+ioVHqxgi44eNXrBCqHZsQMczoLy9ftATpsSGbFWK+VkRyyrNdHWsSZJPOsLq+uP19+
fPcaQzvl6aiEvmkVx7DKUWl/MMZJxX+EINagZQ7OvNdbRWuLe0b5N5V7NJ3/D2p1tmWZ6+VgAOhu
K6/vZ8lAEi0UtBsScKAtSfrq/CBgyAI/EaBqkdgT+3CMXBVlpAhDT1bNl3jFRZOgxmpdrNMnn1Ug
XitfjIfCnSyHw+VkIt68vxajoTulBUlWBufk9Sh1wnIpVhfCODtNGmZOnhXlubtwxyMa3G2hixMj
v59nYUgj1ANWKYK0reelv42QTRNkZX2OspwoUV/gkDuj5sZhnbszGkahoEvAxEEa9ylT0ZTZkcg7
S0+fj4bMJo6znRPG0WbbsDZ0ZRolMj7mlWRePUDGTNAWnjOZMCsgajNmCaH7DPysaL7z29zuDqIw
jCBcuT93mRrHLqqhUH2WUbrR5zTMZYRDCD1HdomDw5hWKmgtoe74/Nd3L69pyKDP+aNSxd7ys0OF
T6YwwtDvfi61BuXg/D/4D+yBQs6h4thupBjTxOz+PokJGoJgKUwpXRVsYAaHgBnE20RuIpiezh9Y
EfAT9CW1WujSFbdaOCCNH7IUvmn3PSWi1I+rAOAC9XuYJFpXFCjpMuA+TS1D1RMZZgpNJAU3SmKf
VYWlJaJQ4HSiMGIOOJgCuIn3RPgDOrea3CBQocTRaLHL0r+XQua5koUgy6A1JNXivWkYI23U3m1V
Kqp8U8gABPrrlFBuiC3XqXhyvS0U0I0hSBHLdFOhzhR0qcAWsx6hI3xT2xlH303ria2vtsq3Whxv
hAC146u0v4tuolwFkexnxWZAXwMqlr9l4be3V5ffZuOFM/pG+2DGhtBSrBGpNusOMfq8pYBRiDIT
1DkLaCmQlNm+aHZSzSWfmWZrsqSQA79Uabvn28hXwtRuNJKAsPGMA8sQPgVcCL2tSqQ/+JTp0UkY
EyTQkmdaBX0gR6Y3mk1ETgtRSGscbRtiVpy/GS1ekjsLiiO02iZAcRtJ8U/yBixhr3DszFJQgKaN
V1vsk4RpjYpCWKHMyUpLiG6kNLTMgRs2BnIOVlIfRGY9TDgQyIMOB/IX7H81HRhIUFwQQDcARKJ6
e2Fhh+XWW5vZg9WefI5wLlkKBMogEIXSBqgkJhV4EEci3HOYFICnp8geMKD6o5Ixnd4mQmMjkA0q
JbqWJQL3MxA3/BAlFAVnB4e/QTu0xCxx/lAlHg4H3vdS71P/WuobQSUv/K1P859wZvasjJK0alsg
OVdAEFbrnuAgJmywA8J7MEMCq2nKtWwWpDUaS6o0MvcvTPuKEQZ94ItFdofAXCqYAOqwZ6SNaGRV
I87bkByalpDj9kRU/h2WKwveFShKGQzak72iCw3o5nFEFmEdHKvlkimRc1OUL/bs2m/izINhKakL
Mwz0JVFJISxB/vX2JQQSV0aUITOPNB2vCQzQaRexYGxsQdnI0Kntr9kuYQS4APqK2lKiEiKk1BzN
8UOZikG7yaBHRp5ENgOfDQvpsGBLMVxzZOEYXiIyyeD/ufhUIP1EeMqy/yvhUS3kzN9GtkYeS00L
uBRlShXU0hDPWiR3OJoYqVaqiDLOXuSLmhj6HL+tdI2/uWCFUBMQxniFA39QxtM46mcpAhg8FHaj
6PCYWY05UTzFnBDI182yNadnogHvO3iyCUfE4ZJCCCVEXt6/v5jUtmUsTJgrn/KmZrOQrMbGZm+j
ACypcn1QE/Wh0VM/e1Agq/XYaL2RhYfzd9CaxaagIw970KoMJxLF7hF2D3w3kWnFGbotBYqXClh4
1qtjwgkYLBpMXA3DOjYkB5T1xaVJj/wFRGyzKg4aQSJEkF0qDqITbkXOkkPBGXpF1lE8+ZU94V5s
ZKyY3Y1SYZEldYilvXbeaUel1plCCXt0p1B4AD+tfVQU+9sKqdbY+x2jngIiD5Jk1H+QNsIUzz12
zwL1ijaLHCoZqPQ50CJS9TFbR1nMrJyvM7Pt9PgoCVBhZba1KRgudtn/gc6ciNAgALtGa4uFmhFN
NNn7p6TWqb0Daio9QCM2mdCjlwQuRPgiCwkQeLJRiR3Q1LF21gQjTzU5kcPNk3b4qmfI8Yt9SbR7
wnFbYKbcx2ydshYFYWU6M1HlkGu5baBEF5hwZw/Q7MWglakvfkNnBPOeo3QGcF+tPvWwFxJ4iD+7
KCi3JmqzfzfkHSa/FGe2MDiUDKacay3ti5cB/Gkr43CAnsBUMYECziwjsDT4y9K2QzbZuUWrVSdd
3JHzURkk455xbGJs71xQWxYczTLO9Z9W6aquFA4lPhVBtGmHWL+m+j7NHfvZrsnQzCmv2ixt0fFC
uFRs2MxCVSVP1xWl5ji2VXWlubZHgTRyqBO1GGh+duiJwcY3pkVcC3SLad0GHrUZqi4iSW5oYhos
XmrhRerygdtnNK5beYtjtixFgqmNbT+gEF9hkLiAHEDKQUke0UfkpAaubLGHMcv70rCP8tE9+XB5
fbEUHHXxX79CL5aiF2NCUZLHXMGyeJZzI15zxC+PTstHs4BIYnVlFHFKgiSEmpKQMxraFEKhzGQm
ghG1vDRu05H1+uPhOoaZWviK3JUU9OjN7cCs68JRHuDSEyNMuA9NqNLvP2On1aotBcPhmihTJ2Yv
LYRCYDL8KPWbk+Se99AMUyDgLoiqJwoHMt7JvTa0LZ0Wjo7iN8PoZZJVaTsBaFuz1UKQ+ESNWgbE
Zvq5FJPHt8oCo4GR3dA4zjrCXYwe3M3oSpVpOz1lqHkqpEjEFzIUsegYGqrmmqYV+kzku5K3SLpU
30XUXStqv/K9vUmwuagpaDhQhJKenOqwaMNYWMW8LNOAqkMuGvkmlXALVlD7DmCAbG2q3zPqhIxv
aJkQVhKOlZRgGv1PDoMMWh/Ge3kn5Kld7BuDCg54OD4LBulHGUSVbm2z5yCtdOykZqvFHa1HtUIx
ie7DnCoPgMWDgOjMlTRM+K7ukAWN4IfGrpa9f194G/92MuIeHf14pez52v3s9jzuaBzWUsz/LWp5
lpt3KrKN+U2p6YTwOmWfdGA9Etrc+jmMI02WJFMm9D5BNzR21LXhge7JlsIUd/WR0nNElaPYMRWf
ASQHD1NoWFqgcka7LEMiOqXPnSRGzSCPycSLgHyzxF7RmR59aYIRXSfQo7Iwo/bKxIDEoNdW8k1w
I1w7dB90PNKkk6PRfJtHaZgdYLDN6OyZZb91O4hCiOVLs3SfUJnPHqJhX90ISn2LnRaHaRYYWJNC
bjbIPvZyoLl2oRqRXtxvHtbGyEPk9EPyxBFiqxHh4k5ScjEflJ0BHnvVvxT2B0/hZKktXIov9NNB
RO1xn/iVKBqXr3Nu+yaSc2xdHJsOpb7Z5dbjoYtN7uQ4ZGtOj4TjBFkzgqA2n7VEZ64sAP8SdBFM
OOX4e+C2FHQbvBw9P+tNF3dub3w37o2eu88DpB3jot0SLbhP7nQ+H4oNDlObr8n0Gd/7qrtSpWQQ
fkF6haDbeofyfPr3V50lQ6LXoavANJDFYcD8+y77RWGktRmRctPMhVEMyPMDmmveksIyb2a3wJh5
hMFERLVAM/W7tu8z5sUJZcs+L5vZq9U7pkmPelng+Q2R3C8Ogn1UoW08MP/0LSypwnDuBf5s6g09
JcN5OJGBmoXDWTifzNUsmIyDMJiPZuJphx5OtHklsuQAQbJC0NI12es/Yn6zs7/ElB6UXCdQt8Kh
J5PRcDoc4yezH/uz+dybeZ4/HgbjmQzH0h9PwiCYeGfe1Dubn4Vqij/MvsxuVIpAZq1Hz4NRbl4z
R/0JfZqnSfM0h993dH9fn0mW0NRwOHbdEb33rV5f2ueuiXkyXW3pQPk9kKx4xXXZf75/13DbBcFd
Q69NG7+pRm8JhpFdEZWtkc9K3hQqNIfEpkIVeCDB1oqa1fRRqrF5Z3WMfJpdXR+2eObCuhnYS36v
oDdKopHb5t3q5A75X/Yl34KsRKhoWCUGc5bGf1F0vVxxdMeSMzIP8f/1grTi2p7pkQo/fvw3BAMd
Tg==
===END CRASH DUMP===

Please help!

**Comment by xZeroMCPE** [comment]
It's fixed
