### ISSUE TITLE
Reset Chest plugin?

### ISSUE THREAD

**Issue by ghost** [AndreTheGamer/SurvivalGame#26]
Please link! thanks

**Comment by xZeroMCPE** [comment]
Will be added soon.. In meantime you could use any chest reset plugin on "Pocketmine"

**Comment by ghost** [comment]
I could not find. Can you send me a link?

**Comment by xZeroMCPE** [comment]
Hi, The chestreset plugin has been added. Check here: www.github.com/andrethegamer/survivalgame
