### ISSUE TITLE
Cant open chest and Preparation time

### ISSUE THREAD

**Issue by ghost** [AndreTheGamer/SurvivalGame#28]
Cant open chest and Preparation time [15 seconds in PvP closed] add please thank you :)!

**Comment by xZeroMCPE** [comment]
Hi, i will try to fixed it.

**Comment by astersx** [comment]
Maybe is becouse of game spawn protection!!!

**Comment by xZeroMCPE** [comment]
Yea, that might be the cause. Anyway i'm taking a look at this issue now.

**Comment by ghost** [comment]
Spawn protection continues to be closed in the same issue .

**Comment by xZeroMCPE** [comment]
Hi, spawn protection is disable by default so player's can't break blocks.

**Comment by xZeroMCPE** [comment]
Should be fix now, download the new release via our main github page.
