### ISSUE TITLE
Deprecated CallbackTask

### ISSUE THREAD

**Issue by idobyte** [AndreTheGamer/SurvivalGame#30]
[WARNING]: A plugin attempted to register a deprecated CallbackTask (Callback#Andre\SurvivalGame\Main::gameTimber)

**Comment by xZeroMCPE** [comment]
This is not an error, It was just a warning. Anyway thanks for letting us know. This does not affect the plugin but i will try to use a diffrent method for task.timers.

**Comment by idobyte** [comment]
okay thanks :) just didn't know if it was just me or everyone lol

**Comment by xZeroMCPE** [comment]
xD , It;s alright. You did the right thing which is by reporting it. Thanks anyway have a nice day :)

**Comment by idobyte** [comment]
you too :)

**Comment by xZeroMCPE** [comment]
Any other questions /issues create a issue report or through skype: andreleon911
