### ISSUE TITLE
Game Events Issues

### ISSUE THREAD

**Issue by CLiu13** [AndreTheGamer/SurvivalGame#32]
On player death, leave-game, etc., the game still considers that player as an active player in the match. Also, once a game ends, there is an endless spam of a "You have won" message.

Hope you can fix this soon! Thank you for a great plugin :)

**Comment by xZeroMCPE** [comment]
Hi, ok the endless message can be cause mostly by (Server Lag). But the issue about the player death,and leave event is still being fixed. Somehow i thought it was fix already. But anyway thanks for reporting i will try to fix it. Have a nice day.

**Comment by CLiu13** [comment]
Thanks for a fast response :)

On Jan 3, 2016, at 8:59 PM, Andre <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, ok the endless message can be cause mostly by (Server Lag). But the issue about the player death,and leave event is still being fixed. Somehow i thought it was fix already. But anyway thanks for reporting i will try to fix it. Have a nice day.

##

**Comment by xZeroMCPE** [comment]
No problem.

**Comment by CLiu13** [comment]
Any progress so far? :+1:

**Comment by xZeroMCPE** [comment]
Yea, i've just fixed some major bugs and added new things such as:
- I've updated the arena setting up messages, It's better to understand. So far i'm still trying to fixed the "Game Issues", It should be done soon.

**Comment by CLiu13** [comment]
Alright, thanks!

**Comment by idobyte** [comment]
:+1:

**Comment by CLiu13** [comment]
When will the bug fixes come out?

**Comment by xZeroMCPE** [comment]
Hi, soon _Few days_ I'm fixing multiple issues at once, but mainly will get done by/before this friday :P

**Comment by xZeroMCPE** [comment]
Just got fixed, download the new release via out github page. If your still having the issue please create a new issue... :)
