### ISSUE TITLE
im sory

### ISSUE THREAD

**Issue by MaryVictoria** [AndreTheGamer/SurvivalGame#36]
im sory for asking do you have tutorial how to set up.. when i do /sg set tap the sign then tap tha spawns.. question is how can i stop set spawns its adding spawn everytime i tap ground.

**Comment by CLiu13** [comment]
You must set 24 spawnpoints for players, a place for a join sign, and a death match arena location. You cannot "stop setting spawns" until you have done all of that.

**Comment by MaryVictoria** [comment]
oh..okay thank you let me set up this..

**Comment by idobyte** [comment]
I'll make one

**Comment by xZeroMCPE** [comment]
Will be creating a "How to setup" soon on the main page. If anyone want to help just fork the project and edit the readme.md and create a pull request here.

**Comment by idobyte** [comment]
i'll make a how to :D

**Comment by idobyte** [comment]
i made a how to @AndreTheGamer and made the pull request

**Comment by xZeroMCPE** [comment]
Ok, thanks..... will be merging it.

**Comment by idobyte** [comment]
okay

**Comment by idobyte** [comment]
you merged my whole patch lol

**Comment by idobyte** [comment]
@AndreTheGamer

**Comment by idobyte** [comment]
i'll fix it xD @AndreTheGamer

**Comment by xZeroMCPE** [comment]
For as of now, i will be working on extending it. And mostly fix some bugs.

**Comment by idobyte** [comment]
okay @AndreTheGamer i fixed the patch you can merge it or don't lol but it's fixed :D

**Comment by xZeroMCPE** [comment]
Ok, man.

**Comment by MaryVictoria** [comment]
thank you...

**Comment by xZeroMCPE** [comment]
We've just added a setup video, check out our main github page for the link. :)

**Comment by MaryVictoria** [comment]
thanks
