### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by austina1212** [AndreTheGamer/SurvivalGame#37]
When I win it does not tp me to spawn and it spams the winner with the win message :( I hope u can fix soon

**Comment by idobyte** [comment]
give it time it will be fixed

**Comment by MaryVictoria** [comment]
yes it is..

**Comment by austina1212** [comment]
Thanks!

**Comment by xZeroMCPE** [comment]
I think it was due to LAG. Anyway it's fix.. Download the new release via our github page.
