### ISSUE TITLE
time start and end

### ISSUE THREAD

**Issue by MaryVictoria** [AndreTheGamer/SurvivalGame#38]
i dont seen time start pop up or time limit..can u add?new player get confuse of it why they cant move

**Comment by idobyte** [comment]
so you want a message saying "You Will be released from your spawn when the game starts?

**Comment by xZeroMCPE** [comment]
Hi, i will be adding a better messages, that tells the player the current status of the match. I will keep you updated. There should be a release soon..

**Comment by MaryVictoria** [comment]
thanks again

**Comment by xZeroMCPE** [comment]
Just got fixed, download the new release via our main github page.
