### ISSUE TITLE
YouTuber (read)

### ISSUE THREAD

**Issue by austina1212** [AndreTheGamer/SurvivalGame#42]
Hello I will create a YouTuber vid on this PLUGIN and how to set it up if u post it here I have 58 subs :)

**Comment by xZeroMCPE** [comment]
Ok, sounds good. :)

**Comment by austina1212** [comment]
Well never mind my server is doing the samething :/

**Comment by xZeroMCPE** [comment]
fixed

**Comment by idobyte** [comment]
i already made a video on it @austina1212
