### ISSUE TITLE
death match started

### ISSUE THREAD

**Issue by MaryVictoria** [AndreTheGamer/SurvivalGame#43]
PocketMine-MP Crash Dump Fri Jan 29 01:41:31 UTC 2016

Error: Call to undefined method Andre\SurvivalGame\Main::sendTip()
File: /SurvivalGame_v1.0.7.phar/src/Andre/SurvivalGame/Main
Line: 618
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SurvivalGame v1.0.7

Code:
[609]               $this->sendTip("§6deathmatch start in §b2 seconds");
[610]               break;
[611]           case 3:
[612]               $this->sendTip("§6deathmatch start in §b3 seconds");
[613]               break;
[614]           case 4:
[615]               $this->sendTip("§6deathmatch start in §b5 seconds");
[616]               break;
[617]           case 5:
[618]               $this->sendTip("§6deathmatch start in §b5 seconds");
[619]               break;  
[620]           case 10:
[621]               $this->sendMessage(TextFormat::YELLOW."[{$this->getConfig()->get("prefix")}] Deathmatch will start in 0:10.");
[622]               break;
[623]           case 0:
[624]               $this->sendMessage(TextFormat::YELLOW."[{$this->getConfig()->get("prefix")}] The deathmatch has started. May the best one win.");
[625]               foreach($this->players as $pl)
[626]               {
[627]                   $p=$this->getServer()->getPlayer($pl["id"]);
[628]                   $p->setLevel($this->level);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #1266 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-3569041 #1 SMP PREEMPT Fri Dec 12 20:16:40 KST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
Slapper 1.2.8 by jojoe77777 for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
SurvivalGame 1.0.7 by AndreTheGamer for API(s) 1.0.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
ChatMute 1.0 by MineBlock for API(s) 1.6.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWgtv28i1/isDeYHaF6Ik6mVbCy/g6zi928YbNXYQtOHCGJEjiWu+lkNaVhb57/3OmeFL9rZp
NgVu2oXFMzPn/Rzyt14Rxqq3cKez6Wjizs/dfk/leZr3Fr/1in2Gpd71/fW7d2/f9fq9WGktNwS7
klEkilSUSaDWYaICEatimwbiMgly5Xm3Zf4YPsrozzLG040Mk8VCqyS4C7PjE2BahxGhGbb33T+6
g9HgdJBtZT7UuT9kXJ0tQ8KE4xFI9hZz9+xzv5dF5QbARa+9EXv8NFAkxXx0jkWvMP/7rtiG2vmh
4sXreeVoJE/ngZLFNpaFvxW6kHkhwkSYpdVYaOWnSaC93sn3QDx3Ry2Eq1zJBwN2a7AvtRKTBUPH
f4z65Bn1ycvUp13qU0N99seoz55Rn79M/bRLfWaon31r6ufPqHsFLYxHXfruiBkYuy8zcGMc+fhO
PRWv0xzUF4u/X7958/bDwOt9/M3u3KjiKk3W4eb4hB/Ac5bD3Z/AzuefxauG8V2IcKi5Hy3c0aBi
eTx+UWHjSZdhy+/0v8jv3VaJlrK3UhuWVTAQN3IvCqyvlC5EmihIlDQitJ1onUIGf3tsaWaR3Ktc
CyD7LotOeHvbRX5jyGkLAsGyi4bjW5U/qtxyvGRsx8D00euFgdf72XJwdoCA1FK8UY8qqhiJ6AG7
kRGKXPoI/Y+9o5E4PlmILPUfVBEjZyAxMTnnBz+XevuqjLPjVZpGSiYnvZ/7vY1KVC4jShvYpcOU
8oo7gI8+go1VGUYBcuV4PkfaydMi9VPsnZz1ezILeac7GbjYuQkLPI6+8B8O5PIhCld0BgmQAGVC
WWzRexMm5ZOIUl9G2xS2mSBFTlxnMpufj6auOHLF7c1SLN9dX98s78TrPIRb+sIdizG8cL6YjsRf
b+/w4E6FzOPH0wi4s20GzLPBfDDG0yf4Fx7HeByZxftUV5QB4AeJVJyGQa/Ot5p0dI3gTOP95fJH
erIct4D9lhbHYPwcEFmiTuSazAM/W+E/Ujzr72OPCgAxAUXav+P6r8t/J/Z5Yp+n9nmKZ+BRiVxF
CvIUean6vUBlkI6IYU2n6+JVGxBLrhuWDc9ThnPw4nkdKaJUkoqWb2/vPrx99+YVQDu10mEBeZMy
iqCVG5nsP6R5FOiWKlrAQ1VMuqqQUVhG+44mXFLFV4pk0HleDAZ2zIApwl8mC5KNSopQRvpu2ZKm
A+53AsRYq5GnI8f46+Vok4R9ugx8gSSv1OMdwrttkxp0IMHoQITekrPGDbKGuFMy7thm8vXeVtH3
vBYnVpTbu8t3d++XbUF626LI9GI4RErZlquBn8bDhrNhjQPCLstcLVUet6VtYIcGc8ddcefT169H
o64HTr7ecvcGn+fVHLR+/ucS00mTd4YNFpI5zcrsMlJ50ZG6Be3KfRB2149pdAsJet/KYVuUDyPu
90SFpLvdbqDACmEdFA8k2G0ks0zlLaEqSFeg8eCsK9Iv6S+pOqV/30wobShTOvnSFHJV6iKNnxmm
A+4KMv8vW6ZN2vMOGPk6E7XnjZadumNIW0YU966UPOGgL6O9+bM6+JWS/u4I9m9M91LgUd3HYKc2
xOBQW5T0RBrg2nYdhMVlXrQ00AEfamB0v1KFvEdHdX80mh447/L6RmY3aRB8O21kKpZZzCg9j2uh
Amdoez3vgM//VDctZoe3MQZi5x9XTpWlilypYSx1gcUOHQqOrSxuyqLtNDXoQF1d9VDK/1/0gg8d
5cy/Xjk1QkSE5aD59SUqgUZqHINPnwaokxDwMniUia+Cv4ad6O+A24KiieN2riVqVPpyfJapb5cA
2tS/Oh5qtoYdYT5TXyxziAl7V3zwpDHAnIDcWYSK2uijZf0kzKgm6CbEy73kiHr3v8hEjM/FyMVQ
sZhMxfu7K+rd57TB4HNIlxdmPnbNn2gZJune/J5ePqTml7q5Wl63zmVpXly4o7E7JSBFMIJCXYzo
KZZPjh3ksIVBOpO7xKEhR/kFrHQxM/DdFrqJQl1cpOs1AYwpnF9Lle8v0qQFytFCW0igtJ+HGSNi
bsFmxV+cFsEzoGWabqAuEhp4I94KnvO9E4VxCFnGZzcEjBBkTpkFslAVTzJJ0hLGsUI5mFdDjIcx
ukdtOXoM1c4JIAcZEULzsShKd846Cjfbwm4zapBJCA50BxanqwqwlXngYyyuyGePWSV3uF6HfhkV
+wuX1c7zZZHmDsbXIkw2+oJFoNnVWJYzVAPTSgWtLayP128u7whE+h1kUmucCS7+h/9BiLJIHS0f
lWWBDea0LYYJHqqpPcBCafSr5+TBPo7IXQWFifDZU0swDvuxwwrgEE0b6tws4cB0waCVqCTDvKn4
TgGzlcYPWQifDFOIlRJh4kclMjFdlzwLFMJ1m8Y4uSYEhzi1XKu+SLGSa0Ip+FZF7NMyt7hEuBaQ
LVyHTAG2yeHFGIiA+Ce1q9ENA7WWsI4WuzT5UyGozZG5IBXGEBYzd7QH+4JuGIzcu61KRJltchkA
wcBLyFUNsoWXiKO7LfK+EwEELiKZbEq5UYKuIlll1q11iGee6cNPrFQ6erVVvpWiexAMVJlIJYNd
+BBmKGFykOabIT0N38C49+n6/sfbt/fzybkzvqdzUGONaCE85MyN1yNCH7ZU0XO6vqW7JSH57ipn
/Ra5TNDuFdAbL7M2mVPwgV+qYJOieoe+Elu0BxEbOQZi41cNyTVCRgGut2URpBQy5haLmDHXMMKP
Uq0Cw9YlRZ8gRwUnwt4yiMdQir9RbsEWzjGOXVkIyv108HaLc5K8VKfgxlIxppIWkSg1nBB1Ao7A
0mGwt1fWpKdmwQFbKzDVoL/mbFbhgcSCYl3AXeERxOpqL6wfYbvNffVqo4ajD3RJmCZwKRkEIlfa
eB6xCV97ADsSDRZnKQF/WynSB5Sufi0lX7ZvwkfsRf9VKnFsSaI8nAC5oYecqyjPO7DmZqPyBVaJ
8k9lvIK2EU6Xep/4d1I/wOPzBwTQgNbfwwjsn5WQtGubp8iicAns1n3BiUnYBAaX7UMNMbSmqYaz
WlA4CRaXCSKHtjDuW3YZyIPgytMnJFLUjz2Jw66e1KyRVg07P64pQmkLRWJfhMWf6G1DzqcCRRWJ
vfDgrDiGBLCzGJNGWAbHSrlgTBStpoRwrP45SldQLPULwoAFVxbKSTE63tW+AEPi1rAyYuKhJvOa
SIdMfO9rlS2oeNgKZUGa9bIO4S5IU8jgCaNaI0dUFI35IUzJTrtJIUdKoUE6A50NM2lK3kKMPE4V
nJULpBoZ/D9nn3qvf8E8Vc4/xDymuIzp21RV82OxaYGQohqJLGO5IZoVS+iHpoarpcrDlMsRxaIm
gj4nZMtdHW+ufSdBPsY7HMSDMpHGaTxNkMAQodAbZYffU6tRJ6pzxBmeYt1s87jgEg5EXxPJJh0R
hbeUQqjC8fbB880ktu2QocJM+VQINauFeDU6NmdrAaBJlelGzMmoevdy8iJDVuqJkXoj8xXs7/hp
FJl+kSLsRa2yOxEr9oywZxC7sUxKLrltLtCOYBbRJ/0qJxw4g/UGk1fX6yo3xI2XDcRbU+/4CR6x
TcsoqBkJkUF2iWhYJ78VGXMOAeejkZFRHL3mSHiWG9lXzOlaqHWexlWKpbN23WlnpZZNIYQ13aEr
vOA/rXPUuPvbMnnQRt9v2OspITKQOKMJh6QRphfuc3jmaEC02eRQD0C9TIOLUFVmtoFyPrd8vkrN
sUPzURGgTskca2MwVOy2byAzFyLHR0+vjNTWFypCtFBX73+JyksSVZAt6tYNrhGZSriid2TciEjq
clEA4U82K3EAmsbUrppktFJ1TeR0c9ROX9UKBX6+Lwh3Xzhuy5mp9jFZp6hYQVqZzU1WaWotjwJU
6AKT7qwBzVkALU8D8X8YZKDeC/TCcNyr5fs+zoKDFfLPLgyKrcnaHN81eofRL8SpbQyalkGzYlpb
B+IyQDxtZbQe0jtD7mICBT+zhEDS+F+atAOyrs4tXK0+6fqJgo/aIBn1TWAT4Q9hgi4SYsFtFLs2
1fr3y2RZdQpNz05NEB3aIdd71LAnmWMf2z0ZDaarcrOwTccPwqVmw1YW6ip5ueooNeexrao6Tc+a
AmWk6RO1GGKmLEo4zHDjG9UirwW6RbQa7Tpzg6qaSOIbkpiJibda9yJx2eA+lFiwh9kjjjmyEDGW
NnaegEB8O0LsPtI9p0lKsoMfmZMmsqJFHsosnnPDMcqmO/rp7d31QnDWxf/9EsNVguGKEYVxFnEH
y+xZyjV7tYkvO9byMUcgk1hZ2Yu4JIET8pqCPGc8siWEUpmpTORGNOwS3JYjG/VdcJXDTC98S+HK
r7rptXtD7NhFoLxApS/GWHBfWlCFPzjhoNWqzQW7wx1hptGqekNOb80NPSr9xpI8xDbTLSUCnoKo
e6J0IKOd3GuD2+Jp+VEnf7MbXcZpmbQLgLY9W8UEsU/YaGSg+xX8XIjp7x+VOaCB4d3g6FYd4Z6P
XzzN3pUoM0eulMG2UvT1gOALFMpYZIYaq7lWaaU+k/lu5SOKLvV3IY3LisavbG+vBmwtqhsaThRr
vnWt0qJNY+sy4m2phqs6FKKhb0oJj2A5zeNwDKCtVPVLSpOQiQ0tY/KVmHMlFZha/gNjkEIrY9zI
JyEP9YIZyOf60PhD1xbspO9kEJa6dczaQVruOEjNUet3tB/dCuUkur6yF2INgxi1lTRE+DKoqYKG
8Wawq3gfPGfe5r+dDHlGxzxeKmtfe57DnuGOhrEW4uyrsGVpVkYWm/1NpekAsZdwTDrQHjFtbukc
9iNNmiRVxsjVBV25WKhr0wPdkC2Eae4qk9JnIGWGZsd0fMYhOXmYRsPiApZTOmUJEtIZPe4kEaqB
DJPxKoTnmy32cs7M6AuTjOg6gT5FEQZqaqx1EuO9tpOvkxv5tUMXPF1IXU460Gybhck6bdyAPiJZ
GJKD1n0fGiHmL0mTfUxtPkeIhn51zSjNLXZZNMvMMHxNCrnZoPrYy4H62oV6RPog5+FlaQw/hE6/
xA/py7gym/jwNHzCrC6MAfLEscW56QAZmmatC6MrujPkSywVpRlVq76gl1J02QJObCtGn06hU1ZQ
NupTQnWeNtnSWpJ1EI8tJMK+0Gj1ECUaTl2YAlclPIuNLGSWK/z6QCn0yvEFlUQhyo2xyvWTpHpr
HqhhAX7LxKLihpfg7DQpL8RH+umgyPR5dP6ZMJosWLUh7dtWFqKaF8zQVl1g8zT20uUtD7dcxTR3
DCR2jEYiBKO2xLdYZ6rMAP8SdN9NocslqaG2EHTpvRh/f9qfnT+5/cnTpD/+3v0+QCU2WeuYXrj5
lGEuzkZiA//W5mk6O+HLbfVUqIQUwm+krlCHWt9AkQu1HlEONr0Fh0y/l/m01T7oX6OwUBPzoZZj
Pgv7ZL7cMl8qrXz0Ndt6P12cJoHMG4D5qLZ6KvOofliHUUFv/IHaNa/+1kVWr27i5vcW0Vu/H/xF
158C0Du0eGXucuvN6An3WdFIUEhiKGiJe7t8w1Tpd+ajl2vO7iEwfx5mf4kZvapzSXLh0Kup8Wg2
muDndz/CbuvJ6UTJWRDMZpOz07k7Hc3l2Wg8ltPVmZycTqfu2Wo8HSnxHSgtt6QW/hiKCac6fGqU
bod1u8ElQd+ptZ00AWV6Z2q29iU61SnIjtanp/7p2dl8NgPpyfl4oiaj1fnpeRAwPb2N00aFmgNL
dyUNjfKxuUgfVII6k9eQD0o+ICMYRQ1mgOwlvyThj2nIDcLMPI0H097nz/8EA7iDuw==
===END CRASH DUMP===

**Comment by CLiu13** [comment]
Same issue.

**Comment by xZeroMCPE** [comment]
Hi, should be fixed, by saturday. Thanks

**Comment by MaryVictoria** [comment]
ok ty
