### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by ghost** [AndreTheGamer/SurvivalGame#49]
Can you give credit to me and @FENGBerd ? 1. you got this edit from when i had it on my github 2. this is @FENGBerd's plugin 
:smile:

**Comment by xZeroMCPE** [comment]
Ok, i will, But thanks anyway for letting me know. You can also help be forking and creating pull request. ;)

**Comment by TylerAndrew** [comment]
how could we give credit to you when we look at @FENGBerds's Plugin and you have no commits? @SavionLegendZzz i don't mine giving credits to the makers

**Comment by xZeroMCPE** [comment]
EDIT: i completely forgot xD please check i just added credits. :)
