### ISSUE TITLE
plugin does not work

### ISSUE THREAD

**Issue by majovec** [AndreTheGamer/SurvivalGame#5]
plugin folder does not respond , nor will fail and the server is not running

**Comment by xZeroMCPE** [comment]
Plugin isn't done yet. But thanks I'll try to fix

**Comment by majovec** [comment]
ok then just write and I again I test.and sorry for the mistakes I use Google translate :).

**Comment by xZeroMCPE** [comment]
It's alright. :)

**Comment by JoshBlazed** [comment]
I know it's not finished but I'll show you anyways :3

Classpath
Inspection result: Passed
Info
Main class scanned: Andre\Main
Main class file found at src/Andre/Main.php
Bad practice
Inspection result: Passed
Syntax errors
Inspection result: Error
Errors
PHP Parse error: syntax error, unexpected 'public' (T_PUBLIC) in /var/www/tmp/5/SurvivalGame-master/src/Andre/Main.php on line 72
Errors parsing /var/www/tmp/5/SurvivalGame-master/src/Andre/Main.php
PHP Parse error: syntax error, unexpected 'public' (T_PUBLIC) in /var/www/tmp/5/SurvivalGame-master/src/Andre/Main.php on line 72
Errors parsing /var/www/tmp/5/SurvivalGame-master/src/Andre/Main.php
PHP Parse error: syntax error, unexpected end of file, expecting function (T_FUNCTION) in /var/www/tmp/5/SurvivalGame-master/src/Andre/Timer.php on line 24
Errors parsing /var/www/tmp/5/SurvivalGame-master/src/Andre/Timer.php
Info
0 good PHP file(s) and 2 bad PHP file(s) found.
Checked with PHP 5.6.11-1+deb.sury.org~trusty+1

**Comment by xZeroMCPE** [comment]
Ok, it's being fix. Thanks for the help
