### ISSUE TITLE
end games ´= spam chat

### ISSUE THREAD

**Issue by majovec** [AndreTheGamer/SurvivalGame#51]
it is a mistake. When somebody wins. and game break. insert it spam chat

**Comment by xZeroMCPE** [comment]
Being fix...

**Comment by majovec** [comment]
dnes sem to zkoušel. a stále to spamu

**Comment by xZeroMCPE** [comment]
Hi, try BukkitPE. SurvivalGames works best with it.. It's a stable software that has a whole new API changes better then pocketmine. 

It supports
- Potions
- Mobs AI
- XP
- Enchanted
- And more+
  Visit: https://github.com/BukkitPE/BukkitPE

**Comment by xZeroMCPE** [comment]
Hi, this bug has been fixed. Please check out the main SurvivalGame github page for more info and links leading to download link for the new release.

INFO: **As of today, Me and my team has been working on a custom version of pocketmine which is called: BukkitPE it's more stable and supports Mobs,Weather,Nether,Potions,XP,Enchanted.. and more. And survivalgame has some features that only works with BukkitPE**

More info can be found here:

Website: BukkitPE.net
GitHub: www.github.com/bukkitpe/bukkitpe

**Download plugins for BukkitPE by going forums.bukkitpe.net then click plugins  (SurvivalGame has been added there too and it supports many more feature) and SurvivalGame has some features that only works using BukkitPE. What are  you waiting for?? Switch now**

Thanks, We've hope that you switch to BukkitPE

~ Andre
