### ISSUE TITLE
BukkitPE

### ISSUE THREAD

**Issue by xZeroMCPE** [AndreTheGamer/SurvivalGame#52]
**Want a better MCPE SERVER Software? Try BukkitPE, It's a stable custom and has more features then Pocketmine. SurvivalGames has some more features when using BukkitPE so upgrade now!**

 It supports:
- Potions
- XP
- Hunger
- Fast chunk sending and loading
- And more! 

**SurvivalGames also supports it, Visit the main SurvivalGame page to download the custom version for BukkitPE.** SurvivalGames works best when using BukkitPE

Try it now! @ https://github.com/BukkitPE/BukkitPE  
Site: bukkitpe.net
forums: forums.bukkitpe.net

**Comment by dries-c** [comment]
imagicalmine and genisys and clear sky have it to

**Comment by xZeroMCPE** [comment]
But, BukkitPE is more stable.
