### ISSUE TITLE
death match started

### ISSUE THREAD

**Issue by MaryVictoria** [AndreTheGamer/SurvivalGame#53]
PocketMine-MP Crash Dump Tue Feb 2 03:40:57 UTC 2016

Error: Call to undefined method Andre\SurvivalGame\Main::sendTip()
File: /SurvivalGame_v1.0.7.phar/src/Andre/SurvivalGame/Main
Line: 618
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SurvivalGame v1.0.7

Code:
[609]               $this->sendTip("§6deathmatch start in §b2 seconds");
[610]               break;
[611]           case 3:
[612]               $this->sendTip("§6deathmatch start in §b3 seconds");
[613]               break;
[614]           case 4:
[615]               $this->sendTip("§6deathmatch start in §b5 seconds");
[616]               break;
[617]           case 5:
[618]               $this->sendTip("§6deathmatch start in §b5 seconds");
[619]               break;  
[620]           case 10:
[621]               $this->sendMessage(TextFormat::YELLOW."[{$this->getConfig()->get("prefix")}] Deathmatch will start in 0:10.");
[622]               break;
[623]           case 0:
[624]               $this->sendMessage(TextFormat::YELLOW."[{$this->getConfig()->get("prefix")}] The deathmatch has started. May the best one win.");
[625]               foreach($this->players as $pl)
[626]               {
[627]                   $p=$this->getServer()->getPlayer($pl["id"]);
[628]                   $p->setLevel($this->level);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #1266 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-3569041 #1 SMP PREEMPT Fri Dec 12 20:16:40 KST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
SurvivalGame 1.0.7 by AndreTheGamer for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWgtv20YS/it7coHaB1EW9bLNwsUZidMrzm58sYPgEBXBilxKrPkqd2lZDfLf75vZ5UO2WxRt
D7i0RbSvee3MNzPLfh6YJFODwJ/NZ9PT2Wx+MhyoqiqqQfB5YHYllgaXny7fvXv7bjAcZEpruaa5
VzJNhSlEnUcqTnIViUyZTRGJizyq1HJ5W1cPyYNMv5MZRtcyyYNAqzy6S8rDI1CKk5TIHPf3fXrw
R+PRyajcyOpYV+Ex09rbckyUcDwFy0Gw8E+/DAdlWq8xGQz6G7EnLCJFWizGZ1hcGvvPV2aTaO/b
RpblYFmPx/JkESlpNpk04UZoIysjklzYpdVEaBUWeaSXg6NvQHjhj3sEV5WS93bab6dDqZWYBjw7
+XPcp8+4T1/mPtvnPrPc53+O+/wZ98XL3E/2uc8t99O/mvvZM+5LQwuT8T5/f8wCTPyXBbi2jnx4
px7Nm6IC9yD4z+XV1dsPo+Xg42e3c63MqyKPk/XhEQ8gc1nB3R8hzpcfxetO8G2CcGilHwf+eNSI
PJm8aLDJdF9gJ+/sfyjv3UaJnrE3UluRVTQS13InDNZXShtR5Aoa5Z0KfSeKC+gQbg4dzzKVO1Vp
AWJflekRb++7yGeeOenNQLHyvJP4VlUPqnIS3zC1Q1D6uBwk0XLwo5Pg9AkBMou5Ug8qbQRJaYDd
QARTyRCh/3FwMBaHR4Eoi/BemQyYAWBidt63YSX15nWdlYerokiVzI8GPw4Ha5WrSqYEG9ilk4Jw
xR/BRx8gxqpO0ghYOVksADtVYYqwwN7p6XAgy4R3+tORj53rxGA4/p1/cKCS92myojMAQJqoc0Kx
YHCV5PWjSItQppsCdzMFRE59bzpfnI1nvjjwxe31jbh5d3l5fXMn3lQJ3DIU/kRM4IWLYDYW/7q9
w8CfCVllDycpaJebEpTno8VogtEv8C8MJxiO7eKnQjecMcEDCSgukmjQ4q0mG+0hLsZO5idA3Lck
1MOMrJErKk1XxBgPz6S9FV0BW/Ijbx3TWOVylSpIaKpaDQeRKiEvHcWaLmLzuj+RSc4Ev5qEKHUU
ktS9eXt79+Htu6vXmNqqlU4MSb4xptTB8THub1OvRmGRHZPmSG1qTQIea0eSRmSMS8BTke0ubr7v
6d+b7Gs/gUpn+9oj0lb475neQ3Il9/ek/dvnv6duPHXjmRvPMP6D9nJiLJfKSg5Zlss9LX7Lanmd
pjDFtcx3H4oqjXTPFL3Jp6aY7ptCpkmd7vYs4f8JF7DklssMAmxZgN/lAawLObmsoIBRVcOGYWOE
oC9VZRJFMXFw046ExV1BZc2yWuYHd7USb9RKTMR4GkwXweRUvL97RXG4oHVLziMjnV8Dl4BGsQnE
zaWw+NTbUxaVOffP/OmEJsnvMhQ252MaZfLRcwB8PuEZXcpt7hE2qdDA1ueeT9PbDbRLE23Oizim
CWtS7+daVbvzIu9NVbj2ZlekdFglJROygolMRkrUOsnX4oZhlcT3rm9YnMJE5x9UirBR4h9WMCoS
CaCFVedvPc2ovDzPKZulfBqKVTsvTbIECk9Or2kyldp4dRlJoxqhZJ4XdR4qp7mHZJQA+zOVG+1U
eUjU1ougrsS+c58tg4K12Hpxmqw3rRWstWSeQITmrJ3LilUzgWo0CpH0mkPlQ+lWoiSOk7BOze6c
rWyzhykqD8nJwET6nHWgzGTvmj2xm9NKRb0tbJDXl28u3l/d0SxdxaiUWuNYdP53/gNFalN4Wj4o
JwXfrde/XKRomKd1FTdL2N4mwtEuS8mFBcWECNl7a8iOm2YnFqDx5ILzA6ogUKo0yiGhKC4aAB0a
P6QRIV2OQRWBMihM6wh9Acg/Cx6idUtOUsRE4ClNLWM1FAVWUFiApOCySeyKunK0RBIL6JbECXPA
9VTwd8Q7CP+gti25Y3QnEhekxbbIvzZClqWSlSAToghKkFTTHcS3Hsp6bzcqF3W5rmQEAqNlTu5q
iQXLXBzcbSoFa2MKUqQyX9eoywT1Gmwy59o6wZiTdvILG5WOvtqo0GmxfxACNIlH5aNtcp+UKkrk
qKjWxzQ6vsLlfiriT9/fvv20mJ55k090DmZsCQViCZhco6gGow8bSlgcelQ8CsnFacX2RW2U6xTh
FNlltiZLCjnwSxm+UhQ8SahQI+ZRypecgbD1q45ljKhRmNeb2kQFRY0tU0kYBxdhWmgVWbEuKAIF
OSqhhysjxEMixb8JhrCF4chzK4EguKeDtxuck+SlGqWacFzsVUlHCJgEJ0RqgCOwdshbriclO3UL
HsRaQaiO/CUDX0MHGgsKdwF3hUeQqKudcH6E7Q4m29XODAcfqAsocriUjCJRKW09j8SEr91DHIn6
gZFKwN9WiuwBo6ufa8nd9Dp5wF6UF8geh44lcsYRiFt+gGdFCcHDba7XqgqwSpx/qLMVrI1wutC7
PLyT+h4eX90jgEa0/h6XwP7ZKEm7NhUSfA2XwG49FIxNwmEYXHYIM2SwmqaczWZBlqS5rM4RObSF
ad+yy0AfBFdVPAJLkWp2pA67et6KRla14nwfU4TSForEoUjM1/ScUPGpSFHuYi98clYcQgPcs5iQ
RVgHz2kZMCWKVptGOFa/S4sVDEslgrDTgrMLYVKGgm61MxBI3FpRxsw80XS9NtKhEzd2ztiCEojL
Um5Ks13iBO4CmAKI50wqBkY0HO31byhpktOuC+hRUGiQzcBnzULatBeI8ZKhglHZAGpk9H8uPpVb
vyE8Jc8/Jbw2Rcn8HVS18jhqKCzqinIkUMZJQzwbkfzxZGalulFVUnA6oljUxDBkQHbStfHmu0cH
8jHe4SEelI00hvEiB4AhQmE3QodfM6s1J7JzyghPsW63LTnhEg1EXxfJFo6Iw1uCEMpwvH30fDOp
7YpimLBUISVCzWYhWa2N7dlWAVhSlbpTczpuHleOXhTIaT21Wq9ltcL9e2h4U1tZUoS9aFV2JxLF
nRHuTEHFY15zyu1LgXKkhi8cDRtMeOIMzhssrsZxgw1Z52Uj8dbmOx7BIzZFnUatIAkQZJuLTnTy
W1Gy5FBwgQ6cdRQHbzgSnmEj+4o93SoVV0XWQCyddeteH5V6dwol3NU9dYUX/Kd3jir8cFPn99ra
+4q9ngCRJ0kyamdIG2Hr4SGHZ4UCRNtNHtUAVMt0tIhUc80uUM4WTs7XhT329PooCVClZI/1KVgu
bttfoDMnIi9EXa+s1s4XGka00Gbv3yS1zHNl6C7a0g2ukdpMuKJHMC5EJFW5SIDwJ4dKHIC2MHWr
FoxWqs2JDDcHffhqVijwq50h2kPh+T1nptzHbD3TiAJYmS8sqnS5lrsBSnSRhTt3gfYsJp1MI/FP
NDMw7zlqYTjuq5v3Q5yFBCvgzzaJzMaiNsd3S95j8oE4cYVBVzJoNkxv60hcRIinjUzjY3oU5Com
UvAzxwgsrf8VeT8g2+zco9Wrky4fKfioDJLp0AY2Mf6Q5KgioRbcRrFrU65/f5PfNJVCV7NTEUSH
tsD6JRXseem5Yb8moxZ2Va8DV3R8K3wqNlxmoaqSl5uKUjOObVRTaS7dVSCNdHWiFsfoK00Nhzle
h9a0wLVI95g23d1e36CaIpLkhia2Y+Ktzr1IXb7wEEY07GHuiGePBCLD0tr1E1CIH0RIXLgcnJRB
Se7RB3JSR2Z67LkjfyYNxyhf3cEPb+8uA8Goi3/DGs1VjuaKCSVZmXIFy+I5zq147RVf7N1WiD4C
SOJ0ZS/ilARJyGsMec5k7FIIQZnNTORG1OzSvEtHLur3pxsMs7XwLYUrv2XTu3rH7NBHoLzAZSgm
WPBfWlAmHB1x0GrVl4Ld4Y4oU2vVPIHTs7jlR6nf3iQ3sV13S0DAXRBVTwQHMt3Knba0HZ2eH+3h
N7vRRVbUeT8BaFezNUKQ+ESNWgZ6Y8HPQMx+/aisMBtZ2S2N/awj/LPJi6fZu3Jl+8iVstRWij4P
CH5DIcSia2ip2peVHvRZ5LuVD0i6VN8l1C4rar/KnXsacLmoLWgYKGKpDVuV7eJgLK5T3lZouKpH
IZqENpVwC1ZRPw7HANnGVD8V1AnZ2NAyI1/JGCspwbT6P7kMMmhzGdfyUcindkEPFHJ+6Pxh/y7Y
Sd/JKKl175i7Byl6z2b2qPM72o9qhTCJnrDco1gnIFptJS0TfgzqsqAVvGvsGtlHz4V3+LeVCffo
6Mdr5e7Xneew53lP47ICcfqHqJVFWaeOmvtNqekJ4WXOMenBeiS0fajz2I80WZJMmQGrDT25uFnf
wQO9kAXCFnfNldJ3nrpEsWMrPuuQDB620HC0QOWETjmGRHROw60kRu0kz8lslcDz7Rb3OGd79MCC
ET0n0LcmYWdtjnVOYr3XVfItuJFfe/TAsz/TppO92XJTJnlcdG5AX4kCy3LUe+9DIcTy5UW+y6jM
5wjRsK9uBaW+xS2LbpkFhq9JIddrZB/3ONA+u1CNSF/c7l/WxspD5PRL8pC9rCvzFT89DZ+wq4G9
gCr3XHLuKkCeLcreg9ErejPkRyyVFiVlqyHG0IBe6ExTitG3UVTKCsZGfsopz9Mml1rtG7fsExHu
A0avhqhRcGpjE1wDeI4a3ZBdbujrJ0bZbrcvmSRNkG7srVw+Ssq3dkAFC+g7IYJGGl6Cs1OnHIiP
9NNDkhly6/wjUbQo2JQh/ddWVqLpF2zT1rxhczf20uMtN7ecxTRXDKR2hkIigaAuxfdEZ64sAP8S
9ORNocspqeMWiDdXF3fB5JuT4fzs0R9OH6fDyTf+NxEysUWtQ1MpDIAw56djsYZ/azuazY/4cVs9
GpWTQfj70yvkod5HTnKh3hDpYD0IOGSGgzKkrW6gf04To6b2S6xnv/v+Yj/N2g9xqxB1zabdTw+n
eSSrbsL+XzPNqK7SdhAnKdycSfv2615synZ1nXW/N4he+70Um37S7uOp/QKYrexbbrsZNeGuNJ0G
RpJAUU/d25sr5kq/yxC1XHd2B4X5+6/7JeYjko40Fx59r5qM5+Mpfn71Pe4tnp5MlZxH0Xw+PT1Z
+LPxQp6OJxM5W53K6cls5p+uJrOxEl+B082GzMLf+phxoZPHzuiuWXcbfFL0nYpdp4lZ5neq5nEo
UanOwHYcn5yEJ6eni/kcrKdnk6majldnJ2dRxPz0Jis6E2oOLL2vaWKNj82muFc58kzVznxQ8h6I
YA01mmNmJ/kjCX2KpQ2/JKUdTUazwZcv/wXb6d5q
===END CRASH DUMP===

**Comment by xZeroMCPE** [comment]
xD, that was suppose to be fixed... Anyway working on it now...

**Comment by dries-c** [comment]
fixed

**Comment by xZeroMCPE** [comment]
Hi, this bug has been fixed. Please check out the main SurvivalGame github page for more info and links leading to download link for the new release.

INFO: **As of today, Me and my team has been working on a custom version of pocketmine which is called: BukkitPE it's more stable and supports Mobs,Weather,Nether,Potions,XP,Enchanted.. and more. And survivalgame has some features that only works with BukkitPE**

More info can be found here:

Website: BukkitPE.net
GitHub: www.github.com/bukkitpe/bukkitpe

**Download plugins for BukkitPE by going forums.bukkitpe.net then click plugins  (SurvivalGame has been added there too and it supports many more feature) and SurvivalGame has some features that only works using BukkitPE. What are  you waiting for?? Switch now**

Thanks, We've hope that you switch to BukkitPE

~ Andre
