### ISSUE TITLE
death match started and after killed

### ISSUE THREAD

**Issue by MaryVictoria** [AndreTheGamer/SurvivalGame#54]
PocketMine-MP Crash Dump Thu Feb 4 01:13:18 UTC 2016

Error: Call to a member function getInventory() on array
File: /SurvivalGame-master/src/Andre/SurvivalGame/Main
Line: 1185
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SurvivalGame v1.0.7

Code:
[1176]              {
[1177]                  $event->getPlayer()->sendMessage(TextFormat::RED. "[{$this->getConfig()->get("prefix")}] This match already started!");
[1178]              }
[1179]          }
[1180]      }
[1181]  }
[1182]  
[1183]  public function ClearInv($player){
[1184]      foreach ($this->players as $player){
[1185]      $player->getInventory()->setItemInHand(new Item(Item::AIR,0,0));
[1186]          $player->getInventory()->clearAll();
[1187]      }
[1188]  }
[1189]  
[1190]  public function ClearAllInv($player){
[1191]      foreach ($this->players as $player){
[1192]      $player->getInventory()->setItemInHand(new Item(Item::AIR,0,0));
[1193]          $player->getInventory()->clearAll();
[1194]      }
[1195]  }

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #1266 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-3569041 #1 SMP PREEMPT Fri Dec 12 20:16:40 KST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
WorldFixer 1 by CreeperFace for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
AreaPVP 1.0.0 by wolfdale for API(s) 1.6.0
Parkour 2.0.1 by Driesboy for API(s) 1.0.0
PVPMoney 0.1-Alpha by hm for API(s) 1.0.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
SurvivalGame 1.0.7 by AndreTheGamer for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWulz47YV/1dQeWdqd0RZ1GFLzDhTj492p+usamu7H6LMDkSCEmteIUjLSmb/9/7eA3jI66TJ
Nh+aTbLEA/Dw7gPQz70ySlTPcydT/JmN57N+TxVFVvS8n3vlPsdU7+bTzf39+/tev5coreWGYFcy
jkWZCSkSlaxVIcIq9csoS8VGlW/TJ5WWWbE/PhGAyKKQe+wOo5i2nj5UxVP0JOO/yUQ5idSlKk51
4Z9epkGhDmZP72SUYmccpUSjO5t+7vfyuNoA6vW6K7HIzwJFVLvu+RlmV6X58zOmADrvgFblG0UU
Ot+C2EUs96o4PnG+1SoN7gyHx0v1XN5mRSJLz7u/uR6IVe/7n9+U20jzpqssDaMNbcLgeNXLCxVG
z6veyecfxBKLBDb6WyHjQslgL3Qpi1IFf8KCbww5sw45nw1o3oAMYDa0ADt0eWgHIx6Y7zF/59U6
jvxWD1exkgU0cfwmZw5PjCBmE4s1zEAbaDy2XJlVWkgtXuyY2h0WzDx3VEyCK9+WKnmb/l2mwXGq
doKGx/Q/z7t8e98f9ocnlvMZ6UYI8asIfaL9Mo6P603nh6KYdUUxb0UxH/6yKIDuS2nM3d8rjfno
j5TGfPwV0phPDqQxn1ppwDfKQvpwgu97R0NxfOKJPPMfVZnAfVarB1U8EXq/kHp7XSX58TrLgDo9
6f3Q721UqgoZkwNhlYbYgNUdnAXqCaesqygO4IGjszM4YJGVmZ9h7RjRQuYRr3THAxcrN1GJ4fA3
/oMNhXyMozXtGZwPCFCl5M9e712UVs8iznwZbzNdivFgOBi7znh6Nh9OXHHkioe7hVjc39zcLZbi
tojEtfKFOxKjoeeeeZOh+MfDEgN3ggiUPJ3HwJ1vc2CeDs4GI4x+gsNjOMJwaCY/Zbo+GQAeQIlF
FgW9JvJoktGNn6VZsr9cvKWRpbgD7HekOALhc0BkVW6zQpN6slSt8R8JnuX3PQQ4ZCIgSPv3qPnb
5b/Hdjy244kdTzAGHpXKdazAT1lUqt8LVA7u6DDM6Swsr7uARHIEtWSsVspQDlpWqwMu4kySiBbv
H5Yf39+/uwZop9Y6KsFvWsUxpHIn0/3HrIgD3RFFB/hSFONDUcg4quL9gSRcEsVXsmTQrVYJCNgx
AatVnUX+Oy/X6mkJp+hy0oD6B47hGnV1GFmwr93B18RSyeSAo/HX66g+f7XqUGJZeVhe3i8/LLqM
9LZlmWvv9BSOuK3WAz9LTlvKThscYJb1cxs9q6LDbgfYYdg94PSqUCC0uKVYc6C30dfrrT13tTqg
4TdobVEVaqGKpKu2FnaotxF7foeZs8nt7XD4h/HxyeBbrRoCOp+/X3O000Sd0xYLWL5Eulr8a9Fh
uIYcsvuFle6yOAxkfKi4s6/nt8a3WlkCfo+7LWTxmFVd86shL4OGe8jFdREpvc72XwTQr+TCHvu7
aP/X4g6xc98lvgZ1qQftzmWcb+UhB9vk1eA/scHdraO/a8L+6H/hLgpLBCTYoaWv/fptrB4U2i27
L+rvQ7M7P2SXa/vlVtHa4o/SGiNFYdOh4zdp8DVPozSvyq3aEIGn2qKkUe8zpX5Z4BOdSk0SF1MD
lEIIhCWMEViPFs1ImAZBUMuzKlbp0XJbiVu1FhMxdL3hxBu54sPyiqqTM5o36BwS7AXFadRoYemJ
xY0wVVtnTZ4V5QUK1/GIgERggsbnYkijRD47tnK9GDFE53KXOlSxKa6FLxyXwLstBBFHurzIwpAA
RvzOj5Uq9hdZ2gEVKAfqVYHSfhHljMgQhkYnUKLSUboRbZpx7hZMTlYGFx9VDPkq8VdDGDWNVGIL
w86fOpxRu3mRUtMV824wVuydOEoiMDya3REwRrvoVHkgS1UTJdM0Q6WvLOcOyvgI7V2CAlpbVp4i
tXMCsCux7sJlyaCBzXZOGEebbSMFIy2ZRiCh3mtgSbauAVtZBD7ahXpT/pTbmSAKw8iv4nJ/wVI2
NTXKeAc9QQkR6QvmAdTFRtdcobQwrVTQWcICub65vfzwbklQUsUgl1pjW3DxF/4HjFRl5mj5pCwV
rFunq1w0NxBPYyoWShVv0x4M9klMJizIfYTP1luBdmqfyIgFcLxQcHqEVldpJWrmUGYr6Fah54cH
lFtZCp+UU4q1ElHqx1WgAnyIL5yHcD2QkWQhIXiJU8tQ9UWGGXRkQCnWSDWPYo+IbXGJKBTgLQoj
PgHqKWDvqAOB+Dt0YDW600CFEgrSYpelfy6FzHP0VoJEiI49QqsR7+nKgi2U+d5tVSqqfFPIAAgG
q5TM1SDzVqmAY6MYcmKAQEUs000lN0rQXQSLzJq2jjDmVib6iYVKW6+2yrdcHG4EAXWEUulgFz1G
uQoiOciKzSmNTt9BuZ+y8NPbh/efzsZzZ/SJ9kGMDSJPrBBSN6seHfRxS5GNXY/uOATd3eiyYPmi
Y0x1DHcKzDRLkykFHfhSJasUbWDkK7FFmIxZyQkQG7tqjwzhNQpwva3KICOvMbcpRIwNF36caRUY
si7JAwUZKkUP21yJp0iKf1IYwhIOR46d8QSlBtr4sMU+SVaq0cAKe4pRlbSIEJNghEgjMATmDv0M
ViIhBSSndsIBWWsQ1aK/4cBX4wHHgtxdwFxhEUTqei+sHWG5DZPNbCuGo48RBJ2lMCkZBKJQ2lge
kQlbewQ5EomGI5WAva0VyQNCVz9Wkm/XNtET1iIPVUoc2yORM06A3JyH8KwoITjQ5majCg+zdPJ3
FV/KwZ0u9T71l1I/wuKLRzjQgOY/QAlsnzWTtGpboPGrYBJYrfuCY5OwMQwm24cYEkhNU5ZnsSCh
EiypUngOLWHcD2wy4AfOVWTPiKVINXtih009bUgjqRpy3obkoXyfCE/si6j8M10vFrwrUJS72Apf
7BXH4AB6FiOSCPPgWC49xkTeatII++rf4mwNwVI5IQxYcHahmJQg86/3JQgSD4aUIR8eaVKv8XTw
tIuYMBa2oARis5QFaZZLGMFcEKb4kpGwhIgR9YlG/VtKmmS0mwx8ZOQaJDOcs2EiTdrzxHDFoYKj
crml28T/c/KpNPsV4il5/k/E6zLL+Xwbqhp6LDYUFlVBORJRxlJDZ9YkucPRxFCFVirKOB2RL2o6
0OeAbKlr/M3FUQg1AdkYr3DgD8p4GofxLEUAg4dCbhQdfkmsRpzIzjFHePJ1s2zFCZdwwPtaTzbh
iE54TyGEMhwvH3y5mNi2BTREmCufEqFmsRCtRsZmb8MAJKly3bI5Hlo+9cmrBFmux4brjSzW0L/j
Z3FsKkvysFelyuZEpNg9wu7JqHhMK065XSpQjlSwhZN+HRNeGIO1BhNXw7CODUlrZQPx3uQ7HsEi
tlkVBw0hESLILhUt6WS3ImfKweDZcGh4FEe37AlfxEa2FbO7YSossqQOsbTXzjvdqNTRKZiwqntp
Cq/YT2cfVfj+tkoftZH3O7Z6CogMJMqo8yFuhKmH++yeBQoQbRY5VANQLdPiIlS1mq2jzM8sndeZ
2fZSfZQEqFIy27oYzCl22R/AMycix0ddrwzX1hbqg2iiyd6/imqVpqokXTSlG0wjNplwTS82XIhI
qnKRAGFPNiqxA5rC1M6aYLRWTU7kcHPUDV/1DDl+sS8Jd184bseYKffxsU5Zk4KwMj0zUaXNtdwN
UKILTLizCjR7AbQ0DcTf0cxAvBeohWG4V4sPfewFBWvEn10UlFsTtdm/G/QOo/fEuS0M2pJBs2A6
SwfiMoA/bWUcnqLIN1VMoGBn9iAcaewvS7sO2WTnDq5OnXTzTM5HZZCM+8ax6eCPUYoqEmwtC45m
Gef6D4t0UVcKbc1ORRBt2iHWr6hgT3PHDrs1GbWw62rj2aLjW+FSsWEzC1WVPF1XlJrj2FbVlebK
qgJppK0TtThFX1lWMJjTjW9Ei7gW6M6hdXd30DeouogkusGJ6Zh4qTUvYpcV7kOIJVuY3eKYLZ5I
MLWx/QQY4ssTIhcmByPloCQP8CNyUkdWdo7njvwLathHWXVH371f3njmXRP/+hWaqxTNFSOKkjzm
CpbJsyc35DUqvjzQlo8+ApHE8spWxCkJlJDVlGQ5o6FNIRTKTGYiM6Jml+A2HVmvPwTXMczUwg/k
rsTgWmrVOezYhaO8ckpfjDDhvjahSn9wwk6rVZcKNoclYabWqn475AdFPo9Sv9EkN7Ftd0uBgLsg
qp4oHMh4J/fa4LZ4OnZ0EL/ZjC6TrEq7CUDbmq0mgsgnbNQy0B0LPj0x+eWtsgA0MLQbHIdZR7jz
0au72bpSZfrItTLY1ooeVgXfoVDEIjU0WM3NSif0mcj3IJ+QdKm+i6hdVtR+5Xt7NWBzUVPQcKAI
+TcEdVi0YSysYl6WaZiqQy4a+SaVcAtWUD8OwwDaWlT/zqgTMr6hZUK2knCspATT8P9CGSTQWhl3
8lnIl3JBD+Rzfmjt4VAXbKT3Mogq3dlm9SBF59rMbLV2R+tRrVBMoisseynWEij42dhYEvXYbRY0
hLeNXU374EvibfzbyYh7dPTjlbL6tfvZ7RnuaCjLE7OvwpZneRVbbPabUtMLxKuUfdKB9Ihoc1Hn
sB1pkiSJMkGsLunKxUJdGx7ohswTprirVUqv31WOYsdUfMYgOXiYQsPiApZz2mUPJKRTGu4kHdQA
GSaTdQTLN0vs5Zzp0T0TjOg6gV7ghYGaHGuNxFivreSb4EZ27dAFzyGkSScH0HybR2mYtWZAb+ee
OXLQue9DIcT0pVm6T6jMZw/RkK9uCKW+xU6LdpoJhq1JITcbZB97OdBcu1CNSL9DeHydG0MPodOv
0UPyMqbMKn65GzZhZj2jgCJ1bHJuK0CGZnnnwuiK7gz5EkvFWU7Zqo8xOKAburIuxehHPKiUFYSN
/JRSnqdFNrWaO27ZRSLsk0enhqhQcOrSJLg64FlspCEzXePXL4Sy2+1eE0kcId0Yrdw8S8q3ZkAF
C/BbIryaGp6CsVOn7Inv6dNBkulz6/wDYTRRsC5DuretzETdL5imrb7D5m7stctbbm45i2muGIjt
BIVEBEJtiu+QzqcyAfwl6MqbXJdTUnuaJ27fXS690Tfn/en82e2Pn8f90TfuNwEysYlax2WhMECE
uZgNxQb2rc1oMj3hy231XKqUBMLPwlfIQ52ffpAJdYZIB5uexy7T7+U+LbUD/WMclWpsfp/imF/D
/GR+sGKe6NY+6ppts54uTtNAFi3A/IquHlVF3AzCKC7p8Z3eCM2vPsIyb2Y3Sfu9hfeahzUs+rdu
3rLpsTBZm7vcZjFqwn1ethyUkggKOuw+LN7xqfSd+6jl2r17MMy/irFfYkqvry5xLhx6rxoNp8Mx
Pt+8hd7C8flYyWkQTKfj2fmZOxmeydlwNJKT9UyOzycTd7YeTYZKvMFJiy2JhZ8y+eBMR8+t0G2z
Xr/3EqP3KrSdJqB83kxNQ1+iUp3g2GF4fu6fz2Zn0ymOHs9HYzUerufn8yDg8/Q2yVoRanYsfchp
ZISPxWX2qFLkmaKBfFTyERHBCGowBWQv+ZGEfqJDC36KcjMaDSa9z5//A5CAIfM=
===END CRASH DUMP===

**Comment by xZeroMCPE** [comment]
Alright, There should be a finished version of SG by friday.i'll keep you updated. :)

**Comment by MaryVictoria** [comment]
okay thanks...

**Comment by xZeroMCPE** [comment]
Hi, this bug has been fixed. Please check out the main SurvivalGame github page for more info and links leading to download link for the new release.

INFO: **As of today, Me and my team has been working on a custom version of pocketmine which is called: BukkitPE it's more stable and supports Mobs,Weather,Nether,Potions,XP,Enchanted.. and more. And survivalgame has some features that only works with BukkitPE**

More info can be found here:

Website: BukkitPE.net
GitHub: www.github.com/bukkitpe/bukkitpe

**Download plugins for BukkitPE by going forums.bukkitpe.net then click plugins  (SurvivalGame has been added there too and it supports many more feature) and SurvivalGame has some features that only works using BukkitPE. What are  you waiting for?? Switch now**

Thanks, We've hope that you switch to BukkitPE

~ Andre
