### ISSUE TITLE
ADD PLEASE...VIP

### ISSUE THREAD

**Issue by EndreEndi** [AndreTheGamer/SurvivalGame#55]
Please add VIP slots on the arena or kick a other player on the match, and add please VIP and VIP+ armor on the match and delete inv an ended match...add pleaseeeee

**Comment by xZeroMCPE** [comment]
Thanks, for the suggestions. Will be working on it.... Anyway please check here: www.bukkitpe.net

**Comment by EndreEndi** [comment]
ok
i like you progress!!

**Comment by xZeroMCPE** [comment]
ok

**Comment by EndreEndi** [comment]
how to add me server on BukkitPE Forum on Servers Categori?

**Comment by xZeroMCPE** [comment]
Register on forum first, then goto the server tab then click "Post new thread"

**Comment by EndreEndi** [comment]
ok thx

**Comment by EndreEndi** [comment]
i m done and now? i posted my server on bukkitpe forum
VIP and VIP + you put in this plugin?
when you update this plugin?

**Comment by xZeroMCPE** [comment]
Yea

**Comment by EndreEndi** [comment]
update now? a day?

**Comment by xZeroMCPE** [comment]
Ok

**Comment by EndreEndi** [comment]
add this suggestion to todo list in README.MD

**Comment by xZeroMCPE** [comment]
Yea, good idea so i won't forget.. Anyway it has been added

**Comment by EndreEndi** [comment]
do not forget to put items on the ranks
in match

**Comment by xZeroMCPE** [comment]
Yea, i was thinking of adding a config that let you guys add what the VIPs get...ect)

**Comment by EndreEndi** [comment]
ok

**Comment by EndreEndi** [comment]
man you are a admin on my creation is a server for mcpe add you pm soft pls bukkitpe is ok add bukkitpe on my creation I added you on admin I can help you and you can help me!!??

**Comment by EndreEndi** [comment]
and....UPDATE NOW THIS SG PLUGIN?????

**Comment by xZeroMCPE** [comment]
I did not understand none of he's words... Anyway ok

**Comment by EndreEndi** [comment]
this plugin well done??

**Comment by xZeroMCPE** [comment]
Huh?

**Comment by EndreEndi** [comment]
?
