### ISSUE TITLE
Make phar For people can test and find the bug

### ISSUE THREAD

**Issue by GamerXzavier** [AndreTheGamer/SurvivalGame#6]
Make a link and upload the phar plugin so that people can test and make sure you can fix the bug.

**Comment by k3ithos** [comment]
OMG just use DevTools for once...

**Comment by JoshBlazed** [comment]
Be smart, he may not know how to OPERATE DevTools

**Comment by xZeroMCPE** [comment]
Hi, thanks for the suggestion. I will make a phar file soon. And yes i know how to use / OPERATE DevTools.

**Comment by xZeroMCPE** [comment]
It has been added. Thanks for the suggestion.
