### ISSUE TITLE
Still errors with get inventory!

### ISSUE THREAD

**Issue by CLiu13** [AndreTheGamer/SurvivalGame#60]
Still getting the same error. :/

**Comment by xZeroMCPE** [comment]
Give me some time, I i will be submiting the new update here, Also can you post the error it gives you here.

**Comment by xZeroMCPE** [comment]
Hi, i was able to fix it. Please visit the main SurvivalGame page on github and download the lastest release there, Or visit the release page. Thanks

**Comment by CLiu13** [comment]
Thank you so much :)

**Comment by xZeroMCPE** [comment]
No, problem. Go head and visit the main SurvivalGame github page and follow the installation guide. After go head and test it and if your having an issue just create a new issue. Thanks
