### ISSUE TITLE
On player win

### ISSUE THREAD

**Issue by MHIGists** [AndreTheGamer/SurvivalGame#61]
After a player has won a Arena the server goes in loop of "{Player} have won arena SG-1and cannot continue.

**Comment by xZeroMCPE** [comment]
Oh, wow i thought that was fixed. Anyway it's being fixed.

**Comment by isoz** [comment]
The more he touches it the more it gets broken, the original version has less bugs than this one, I don't even know how is it possible that he is leading the "BukkitPE" project...

**Comment by EndreEndi** [comment]
who this life...in (PocketMine servers world) oioiooo....

**Comment by xZeroMCPE** [comment]
It's all being fixed man, Somehow there was somethings that i forgot to declare.

**Comment by xZeroMCPE** [comment]
Hi, i was able to fix it. Please visit the main SurvivalGame page on github and download the lastest release there, Or visit the release page. Thanks

**Comment by MHIGists** [comment]
Thanks I'll try it
