### ISSUE TITLE
Server::getInstance()

### ISSUE THREAD

**Issue by MHIGists** [AndreTheGamer/SurvivalGame#63]
Its not  an issue actually but its a bad practice and I'm curious why are you using it?

**Comment by xZeroMCPE** [comment]
Yea, i've heard some few Developer tell me that. Anyway i will update it and yes i know it's a bad practice but somehow i find myself using it even after chaging it xD .

EDIT: Any suggestions or tip just create a pull request.

**Comment by MHIGists** [comment]
I'm new to github... Soon xD
