### ISSUE TITLE
Inventory Issues - More Info

### ISSUE THREAD

**Issue by CLiu13** [AndreTheGamer/SurvivalGame#64]
Occurring in latest version. 

`Fatal error: Call to a member function getInventory() on array in phar:///home/mcpe/beta/plugins/SurvivalGame_v1.0.9.phar/src/Andre/SurvivalGame/Main.php on line 1163
`

[CrashDump_Tue_Feb_9-18.17.58-EST_2016.txt](https://github.com/AndreTheGamer/SurvivalGame/files/123922/CrashDump_Tue_Feb_9-18.17.58-EST_2016.txt)

**Comment by xZeroMCPE** [comment]
It's fix, I just made some typos while creating and fixing some issues :D Anyway download the new release and it should be fix, any issue just make a new issue thanks man

**Comment by CLiu13** [comment]
This was on the latest version (v. 1.0.9) from Github. Should I download source code and directly run from it?

**Comment by xZeroMCPE** [comment]
Download the .phar since it's the one that i just updated with a fixed ragarding it

**Comment by CLiu13** [comment]
Fixed!
