### ISSUE TITLE
ChestReset Bug - With Info

### ISSUE THREAD

**Issue by CLiu13** [AndreTheGamer/SurvivalGame#65]
Occurs on latest version, with inventory fix.
_Good job on inventory fix, BTW :)_

Fatal error: Call to undefined method Andre\SurvivalGame\Main::ChestReset() in phar:///home/mcpe/beta/plugins/SG.phar/src/Andre/SurvivalGame/Main.php on line 573

[Uploading CrashDump_Tue_Feb_9-21.12.59-EST_2016.txt…]()

**Comment by CLiu13** [comment]
On a side note, I will try being more helpful and start creating pull requests soon :)

**Comment by xZeroMCPE** [comment]
Thanks, and the ChestReset bug has been fixed, Download the lastest release. Again you found any just create a new issue.
