### ISSUE TITLE
Config related

### ISSUE THREAD

**Issue by xZeroMCPE** [AndreTheGamer/SurvivalGame#68]
Is config being loaded for you guys? Just wanna make sure ;)

**Comment by dries-c** [comment]
work for me

**Comment by dries-c** [comment]
on apple you dont teleported to the match
on windows it work

**Comment by xZeroMCPE** [comment]
Oh,  i was just making sure the config loaded. But somehow the comments on the config isn't being loaded :P

**Comment by CLiu13** [comment]
Works for me :)

**Comment by xZeroMCPE** [comment]
Oh, good i was just making sure.
