### ISSUE TITLE
cant kill players

### ISSUE THREAD

**Issue by ChiefArtz** [AndreTheGamer/SurvivalGame#72]
we cant kill players in the match

**Comment by xZeroMCPE** [comment]
Is the arena setup on another world? Or is the sign location is setup on the same world as is the arena.

**Comment by ChiefArtz** [comment]
arena setup on another world

**Comment by xZeroMCPE** [comment]
Try testing it on the same world, and tell me is that works

**Comment by CLiu13** [comment]
It works.

**Comment by xZeroMCPE** [comment]
Alright, good.
