### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by MHIGists** [AndreTheGamer/SurvivalGame#73]
Server thread/CRITICAL]: Error: "Call to undefined method Andre\SurvivalGame\Main::clearChest()" (EXCEPTION) in "/phar_SurvivalGame-master(1)_ixlfyo5Pt3qTllc.phar/src/Andre/SurvivalGame/Main" at line 602

**Comment by xZeroMCPE** [comment]
Just got fixed, :dart:  Downlaod the new release
