### ISSUE TITLE
Add ChestRefil plugin

### ISSUE THREAD

**Issue by Shock95** [AndreTheGamer/SurvivalGame#74]

**Comment by HittmanA** [comment]
Yes please add a ChestRefiller feature!

**Comment by ChiefArtz** [comment]
u can use FChestRefill

**Comment by xZeroMCPE** [comment]
I will be making a custom ChestReset for SurvivalGame so just hangtight as of now :)

**Comment by Shock95** [comment]
yay :D

**Comment by XiangZhao969** [comment]
Does fchestreset work with this plugin?

**Comment by ChiefArtz** [comment]
yea but lag
