### ISSUE TITLE
god mode?

### ISSUE THREAD

**Issue by ChiefArtz** [AndreTheGamer/SurvivalGame#78]
15 sec

**Comment by CLiu13** [comment]
To elaborate more on this suggestion, I believe that ChiefArtz wants players to be in god mode while the game hasn't started yet (waiting on the pods).

**Comment by ChiefArtz** [comment]
tf

**Comment by xZeroMCPE** [comment]
Ok, i'm also thinking he wants the player to be in god mod even when match has started but instead it will only last 15 sec is that right?

**Comment by CLiu13** [comment]
I believe so, but it is hard to figure out what he wants with just a 4 words: god mode 15 seconds XD

**Comment by xZeroMCPE** [comment]
@CLiu13 Yea true next time @ChiefArtz Be more detailed on the suggestions. xD

**Comment by xZeroMCPE** [comment]
Fixed :)
