### ISSUE TITLE
invisble bug

### ISSUE THREAD

**Issue by ChiefArtz** [AndreTheGamer/SurvivalGame#80]
.

**Comment by CLiu13** [comment]
Players are not invisible when I test it out. And please, provide a more descriptive comment.

**Comment by XiangZhao969** [comment]
I met this problem too, teleported to the pod when i tap the sign, but the others can see me still standing by the sign. And i was invisible in the arena (because to them, my character still standing by the sign, but i actually joined rhe match ... confusing @@)

**Comment by CLiu13** [comment]
Use a brand new server, with only this plugin + economy on the server. I have no such invisibility bug.

It also might be because of lag on your server. Check your timings, and maybe restart the server before a match?

**Comment by xZeroMCPE** [comment]
I think it's related to lag, Or maybe you have some effects on you on which you forgot to remove. Anyway i've tested SurvivalGames with a few friends and like @CLiu13 stated there are no such bug. Also try doing a clean  arena setup delete the config file and points then  setup arena again.

**Comment by ChiefArtz** [comment]
what did u mean brand new server? and i have economy...

**Comment by CLiu13** [comment]
Start a new server, with a fresh installation of whatever server software you use :)

I guess I should advertise this: Use BukkitPE, with stable features and much more! :P

**Comment by xZeroMCPE** [comment]
Yea, argreed with @CLiu13

**Comment by ChiefArtz** [comment]
but bukkitpe have other api

**Comment by xZeroMCPE** [comment]
SurvivalGame is still supported, Just download it from Forums.BukkitPE.net  then click plugins. Or you may download BukkitPE version via the SurvivalGame main github page

**Comment by xZeroMCPE** [comment]
Fixed :)
