### ISSUE TITLE
When the game started

### ISSUE THREAD

**Issue by XiangZhao969** [AndreTheGamer/SurvivalGame#81]
[23:53:19] system> [Game] The tournament has been forced started.[23:53:19] system> start in 4 seconds
[23:53:20] system> start in 3 seconds
[23:53:21] system> start in 2 seconds
[23:53:22] system> start in 1 seconds
[23:53:23] system> ===[+==============+]===                      [23:53:23] system> The tournament has begin
[23:53:23] critical> Could not execute task pocketmine\scheduler\CallbackTask: Undefined variable: Arena                          [23:53:23] notice> UndefinedVariableException: "Undefined variable: Arena" (E_NOTICE) in "/SurvivalGame_v1.0.9.phar/src/Andre/SurvivalGame/Main" at line 548

**Comment by CLiu13** [comment]
Can you post your config file here?

**Comment by ChiefArtz** [comment]
remove the $arena

**Comment by XiangZhao969** [comment]
---
prefix: Game
Main-Color: blue
Arena-Map: sg
Blocked Commands:
- /kill
- /kill all
- /tp
Blocked Words:
- Fuck
- Bitch
- Whore
- Gay
gameTime: 180
waitTime: 300
endTime: 180
sign:
  x: 56
  "y": 117
  z: 51
  level: sg
pos1:
  x: 122
  "y": 13
  z: 120
  level: sg
pos2:
  x: 126
  "y": 13
  z: 117
  level: sg
pos3:
  x: 131
  "y": 13
  z: 116
  level: sg
pos4:
  x: 134
  "y": 12
  z: 116
  level: sg
pos5:
  x: 136
  "y": 13
  z: 118
  level: sg
pos6:
  x: 138
  "y": 12
  z: 119
  level: sg
pos7:
  x: 140
  "y": 13
  z: 120
  level: sg
pos8:
  x: 141
  "y": 13
  z: 123
  level: sg
pos9:
  x: 142
  "y": 12
  z: 125
  level: sg
pos10:
  x: 144
  "y": 13
  z: 129
  level: sg
pos11:
  x: 143
  "y": 13
  z: 133
  level: sg
pos12:
  x: 142
  "y": 13
  z: 134
  level: sg
pos13:
  x: 141
  "y": 13
  z: 135
  level: sg
pos14:
  x: 140
  "y": 13
  z: 138
  level: sg
pos15:
  x: 137
  "y": 12
  z: 139
  level: sg
pos16:
  x: 134
  "y": 12
  z: 141
  level: sg
pos17:
  x: 131
  "y": 13
  z: 142
  level: sg
pos18:
  x: 131
  "y": 13
  z: 142
  level: sg
pos19:
  x: 128
  "y": 12
  z: 141
  level: sg
pos20:
  x: 124
  "y": 12
  z: 140
  level: sg
pos21:
  x: 122
  "y": 13
  z: 138
  level: sg
pos22:
  x: 120
  "y": 12
  z: 134
  level: sg
pos23:
  x: 118
  "y": 12
  z: 132
  level: sg
pos24:
  x: 118
  "y": 13
  z: 129
  level: sg
lastpos:
  x: 131
  "y": 79
  z: 129
  level: sg
...

**Comment by XiangZhao969** [comment]
> ---
prefix: Game
Main-Color: blue
Arena-Map: chim
Blocked Commands:
- /kill
- /kill all
- /tp
Blocked Words:
- Fuck
- Bitch
- Whore
- Gay
gameTime: 180
waitTime: 300
endTime: 180
sign:
  x: 56
  "y": 117
  z: 51
  level: chim
pos1:
  x: 122
  "y": 13
  z: 120
  level: chim
pos2:
  x: 126
  "y": 13
  z: 117
  level: chim
pos3:
  x: 131
  "y": 13
  z: 116
  level: chim
pos4:
  x: 134
  "y": 12
  z: 116
  level: chim
pos5:
  x: 136
  "y": 13
  z: 118
  level: chim
pos6:
  x: 138
  "y": 12
  z: 119
  level: chim
pos7:
  x: 140
  "y": 13
  z: 120
  level: chim
pos8:
  x: 141
  "y": 13
  z: 123
  level: chim
pos9:
  x: 142
  "y": 12
  z: 125
  level: chim
pos10:
  x: 144
  "y": 13
  z: 129
  level: chim
pos11:
  x: 143
  "y": 13
  z: 133
  level: chim
pos12:
  x: 142
  "y": 13
  z: 134
  level: chim
pos13:
  x: 141
  "y": 13
  z: 135
  level: chim
pos14:
  x: 140
  "y": 13
  z: 138
  level: chim
pos15:
  x: 137
  "y": 12
  z: 139
  level: chim
pos16:
  x: 134
  "y": 12
  z: 141
  level: chim
pos17:
  x: 131
  "y": 13
  z: 142
  level: chim
pos18:
  x: 131
  "y": 13
  z: 142
  level: chim
pos19:
  x: 128
  "y": 12
  z: 141
  level: chim
pos20:
  x: 124
  "y": 12
  z: 140
  level: chim
pos21:
  x: 122
  "y": 13
  z: 138
  level: chim
pos22:
  x: 120
  "y": 12
  z: 134
  level: chim
pos23:
  x: 118
  "y": 12
  z: 132
  level: chim
pos24:
  x: 118
  "y": 13
  z: 129
  level: chim
lastpos:
  x: 131
  "y": 79
  z: 129
  level: chim
...

**Comment by XiangZhao969** [comment]
---

prefix: Game
Main-Color: blue
Arena-Map: sg
Blocked Commands:
- /kill
- /kill all
- /tp
  Blocked Words:
- Fuck
- Bitch
- Whore
- Gay
  gameTime: 180
  waitTime: 300
  endTime: 180
  sign:
  x: 56
  "y": 117
  z: 51
  level: sg
  pos1:
  x: 122
  "y": 13
  z: 120
  level: sg
  pos2:
  x: 126
  "y": 13
  z: 117
  level: sg
  pos3:
  x: 131
  "y": 13
  z: 116
  level: sg
  pos4:
  x: 134
  "y": 12
  z: 116
  level: sg
  pos5:
  x: 136
  "y": 13
  z: 118
  level: sg
  pos6:
  x: 138
  "y": 12
  z: 119
  level: sg
  pos7:
  x: 140
  "y": 13
  z: 120
  level: sg
  pos8:
  x: 141
  "y": 13
  z: 123
  level: sg
  pos9:
  x: 142
  "y": 12
  z: 125
  level: sg
  pos10:
  x: 144
  "y": 13
  z: 129
  level: sg
  pos11:
  x: 143
  "y": 13
  z: 133
  level: sg
  pos12:
  x: 142
  "y": 13
  z: 134
  level: sg
  pos13:
  x: 141
  "y": 13
  z: 135
  level: sg
  pos14:
  x: 140
  "y": 13
  z: 138
  level: sg
  pos15:
  x: 137
  "y": 12
  z: 139
  level: sg
  pos16:
  x: 134
  "y": 12
  z: 141
  level: sg
  pos17:
  x: 131
  "y": 13
  z: 142
  level: sg
  pos18:
  x: 131
  "y": 13
  z: 142
  level: sg
  pos19:
  x: 128
  "y": 12
  z: 141
  level: sg
  pos20:
  x: 124
  "y": 12
  z: 140
  level: sg
  pos21:
  x: 122
  "y": 13
  z: 138
  level: sg
  pos22:
  x: 120
  "y": 12
  z: 134
  level: sg
  pos23:
  x: 118
  "y": 12
  z: 132
  level: sg
  pos24:
  x: 118
  "y": 13
  z: 129
  level: sg
  lastpos:
  x: 131
  "y": 79
  z: 129
  level: sg
  ...

**Comment by xZeroMCPE** [comment]
Download the new release, and try it again. If that does not work then use a new MCPE Server Software such as BukkitPE

**Comment by xZeroMCPE** [comment]
Fixed :)
