### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by Shock95** [AndreTheGamer/SurvivalGame#83]
Server Crashes When Players Leave The Server While In Game.

===BEGIN CRASH DUMP===
eNrNPA1T28a2f2XrZO6Fd7GxDRhwh75H+Wi4gcQPkya9USezlla2gr6qXeG4nf73d87ZlbSSSTHg
dB7Taayj3bPn+2NX0h8tFUSiNezt7u3tDfZ6O/2tlsiyJGsN/2ipRQq3Wmefzq6v3163tlqRkJJP
EXbCw5CphHEWiWgiMubnsauCJGZSqEtxJ8KNTQZXcR6GMNEPQpy1Pc6zu+COhz/xSHy663W6nV63
k854ti0zd/s49jJRG7N9xYMY5odBDPP3ujt/brXSMJ8CcNiyB8IYN/EEUr17uAs3HeWowN94qWaB
bP8whSFjxVUuj456mzB493DPDPqDrgbmylFmRsilugHRtNvf04D9akBw1NWwgxLmJ5ng7qxYLg35
QmSSccle3orF0Q8vgUy97GE5Bxfe63bLa8T8r399T9CeDU2PCi6EGovsTmQbm3QxomU2EPlHpxV4
TuvXTT2/b83f3hbuLNl4GXScluPETsuM2amt0f6hVFwhAbzY/J6t8veCnV98ODtlN68uxuzy4s3Z
d999x345/gX+obV2rbUEkLuBpOCiSoQiTTK1AZdGdol0Wh2idvP7ktg9C0EeA6kbL1Nzq1Ldn3Rd
aUrOA1UppdDoJo06aOih0ovLpWC9IUJ7Ne1oNFLE3pX2A+Qi73b5/gBsK1NBPGXtHxgLYqbBE2Sk
vjhwBR7iJrEnC956trInYEe3GtyvU9TXFO08gaLHEAQOpjLugid9bL3oso3NIUsT91aoCFzQcbT9
tX9wMy5np3mUbkySJBQ83mz9utWailhkPEQvhFESwgFQC17uiTsgfpIHodcadsGFs0QlbgIDd/a3
WjwNaFhvt9OFYdNAwWV3xT+YkPHbMJjgnM4+YchjjAjD1vsg9pK5ZG9u2M3xv98fX7d/Pr54ywad
HiNa2P6g22MbxbB99iqJBBtlIgryiJ15AQU0ZDlwAc7dW9bbZMHewQAWSWcpLLHXGXTw6nfQAVz2
4bKrb35KJJJw8ebNDQDoYg5hqwxgEqXUu5M9/NcQTJdbluy6ECH3AMJzNUsymPLxVyOvjyhXWgsE
B/8CXMR8EgogQ2W52Gp5IgWizByZ+OrUBkScYuhVEAd+8CVIHCeJxZ1MUMlvY/GzhP9h4E048jV6
O755//b68hRAczGRgQJyMbYDO8cemMZ5Hlt8lKCtuh0QvRUvrVmyCOKotxu5LZuvXr9gbId+9Gnm
EzksaHEci6qV2LrjsSu814GSNdYssMXebqdXYy3MXd4/SIWqc7bzHEaqlR2nSIx/wUhrplQqh9vb
4FGzfNJxk2i7JGu7xgjye/7aZhOuLO7qvH0YzyAkgCyDTHxY1pzNn89DuTKD569BSbTwKvoJA15T
DF3XDa7fNLj/cPcVuPFf0/wYneCiWhknEFHlqqTP+UKOUz6vOY0FtdnoAxv9OhujWRAGKRvDP1AZ
TdfGTkp4pUHrOJxIkkiS41wCYyKrOBzfHF/fvBvdxx8UkPNXGMYr5grQV43qhKcKqHgt4s9Bb399
GsKFZ4FayWMM/T9yGbiv3p1a9JegZkQb1DXDwyAPF2ujXqNznFnuPdnleSg+c6isE8C1XeXytklD
2yoTYjuCckBk2yWbIIWTGVeXCZXapRgqWF0Ou3UpnN0l4RhYqsvhGWmqXLcphXuMkGQAIpjP5x0B
hCDOjrollqBSyS75dGqzVMLqLPWaseNSQHnjvfWvTkZnrWYafipfxeLL7rWyfm26titukN0kmpDc
piKzObbBDwTMSx5NkrWZM2FzHJuAx/jlScaVeC0WdtivYE3PrNdNrZPTcx5CnQvQ8ue6UnNJxJOd
tCBpe1Q56NWoPTKlIjKfS5VEx6HIavVIDVwXwWAVp3yGNu2lQal1Qp7kn6enb8bvUg+EadurDf1q
+gDx1dP6MxjzvFjmekHHqa++gpWeirsb6IlsJZWgRohZKoi19qEoF+xG8KjG0E6n91SGivWBm4qS
BzTUMNCKsu0SBzB7BjabRIu+xWwJqjcywG6D1yz5LFx1EfvQg6j15cxLISDbF1RUv1bTXjEaStz0
HqYI3GSsv0bGKvGtzCLSVL9akdUoVYv3SYZNecVoBXygeftGpY5AAuZIwKq5/hn1jsUtCiSGDDyC
BBraAqmAzVy5UxfIL4mE0vnw8LC15ia9IuEx2fKc04asBHO02LGhdX52mnZ8I9RMZML7tDYdW4s7
jrlYnSFj4ceji2XHRGDTLbt/t1smsZjQBorQgwF96ZeawFXUFi6gPop4bHulBXzAK6+gFvHBtOXa
ipsSI6jMJuPBNvA8z2LuiovYC1yuEjulL91quFadJyPXGkeDpzNUqsnXVAQFFcDgMl0rqOyV4KGa
4fmCnfRtaLO1aKTCscqCW5H1u4efrhrNxTOyvkWA49SpWYGpCyWiM98Hj7GZsqH1TYq9piV+AGEu
lpql54SPL6AwyBCBWK3Mlh2u2j53O7FQGN5fB2EIYsjsfYkK9oBf/Zjf3gZ04iKvTtbV/tWQOk5J
zGPC/CXPY3c24p6tJgv4YLwYnY0ufloXRwYdtLMlBY9iRvAUY5fFiYE8wMZloFQofgym61OOhRLY
ATIex8nF8Y82G3j5hIKq+/yCKgz45FGUB9OZioN4enYn4przN+88sGHyJrhNbn48WVsiaiwPSlmi
ZyX27sQ4mMZ1xgpYs8Tr/S01bwjrS1z/b9nkq7gFcVzxWBfAtjwsYD3Id5s17zeyWSgxdA/wKJ/D
7vRaSGEH+ApmcdLvPLB58AwWUOwZLgiUW2uvQj7t/df0YCB1q9z7xputZtXHtF/37OW8SY49oFoF
EhwUioCKq+adB8Lizxzs9ffBYG1eVyB0nAYlDcBqWoO+zBV+HjaPc+rwmvHt1lPX6Yelig8bxt1n
RMrTD45TI+AxbqS3ek7h/yfQqyWhsLlautc8ru41zgJmeSSyXH5el38tUfDkmLmEaRnSInGkebq0
72pDG330N952tVZ+3mnINT15U3PNEvRQqZKm4W8pX1vQLNZ9jJnqR1GOgSiLAQtYz1y9nW8cNauV
i6dkDBVP0s04iNJQmKd6bLtr3LD3wzv9GoenuUrWpqD6ssBhk4xVFBaC2dR29gtIs+o6bO4AfE4+
J2If/9bmRlKvjbXGyhZnP3BocVF/DrHuOL2G59AzjjczgYOzdWmHkIJSLEKeXkkiLjUT+Mhkti0N
SrxCu7zh6U1yam8oFpDmIwuNynmdJZbiqUq8xHGqtVfQHj7tdgJdXF5LaDb0gV2adbJgLQts1GhY
lRW9EVfzpzrcrjn+suKwt6i3ylNgrES6a6lEamQ9JsS/e3dx+iOPscWzuLShDXdrbKvxu6B5yvuM
iKHRPYb+nxMlgFKL9gLSDBON7PRT9P5qbXQjMscxK5c/VufgWsx55jWYMECbDzCXZtxuWpp5su9Z
D/SRSVUkrB7oIM7dwbSMpnUiNxUdHdSo1cXHPWt71DZ0SV3tbiM6fGy9hkw4CySVv6YrXtN5tEWJ
49TJetY+wYR75QZBKYfz4ItYEoMGfv3ZrUwA2dk5Pje8Lqut1jU8FzSsYLU0fpSBsl3VZKUAN/PV
iptxW2va8qHdjVTT8jccdNZYr87SLuvHTDa0ufFz+PCZzMqnaHgY9ohztBDoKQ/SLmunTyucFwLX
YJtqscxneafJ62CNvBp6n8Z5aigsubdIXkECeKBwzZVoHHgQqNEefZOdzuJ5FmAJKb7iUgZ3wrBS
F8pW66ck9MYKZXXN49t3aWvZaW6BeHzU6m/ZJi0lVbZj73mWLrViBGwKs7tcOQbZrXyuOM/xpY2M
x9KnSDgOk7l1eSaliFXAQ6nP3IzwfLO440giGLJfWjRwhvgVTOlNosbJechVbSOvgD1wEnCPMQ3W
GEvjRMEQoGOFQFrsceWZGIksqm3plLDmgxHd9vVJwz8Gu+fn3e7y2cYzi5tPGq/jlMRYP5+yx4Vz
jXFXeEAAH1TGIW1zBQ5pyaAGXuplW099DeARErApcJwGPavsXgKX+LhwQ7EEaup1d306taznPr+t
Hrr5iq6RvurXGjRNaP7E1414BmKgR0K04GlzqmNSS4C7S60Xo/KKnSSxH0wZvrLpZE78AqI3OxcT
1ttjvd3hTm+4O2Bn4xvW7/YGOEDja6OsjzCG0+Mi1g3c2TvqHfZ2+gj0AokSbIfJFFc46iEw4l/a
5p3Jox5IBCfjrnXbFEgguyO9GD7KD5MDqY4S30eI1kj7t1xkiyNozypQBtmlGBUlyjv6x6Ckj/2j
X+yW4G3oJpM8doWhos3dWSDuRITHigZpJjypIJG1XR66OQQbJErf4iEE4rYf4nFksaCmn8dBBPHY
jNOwKJkUANxViRJPHBHLfpIBBSXMIJpBs+ImWXmd3qVmthf4fgCkqIWWon77DvqCthQK3/2TRwim
9zi1evRjdSVMCuFZQ/B136PTs/Pjd5c3xDHIr5NCzoZp3tF/0R8wm6ukLfmdMFTg225lIu0sohDN
iWEcZi5ZUp6RrMigGPDILiI+DUCKeDwG9sVuZkIKVtDMeCaYmgkGspbwgyvmonoUmwgWxG6Ye8LD
VxqX7BhxjfENvsRHBE2ckvtiiyX4TJtElIzetWSLJM8MLhb4DEQf+AGtAFLPwPggwwDiN2Jeotv2
hM9B7pLNk/ifiuFGIs8YSiYCXoG1cIEvP+Oblprt+UzELE+nGfcAQceJ0Ts0sqETsxc3Myg82iGA
gAood6c5NJMM32gmiRlPkgFchwngD34nmeLUk5lwDRf1iUBAESZE3JkHt0EqvIB3kmy6jVfbl+BF
nxL/08X47afBzmG7/wnngRhLREPmQMSbOi1c6P2MngfEt77xjVOGb4BLlZF8FVYh4BMgN7pN0iRK
gQ74JRSp1BP0JuUMSrCQlBwBYm321ZL0yhjA5SxXXoIOo3eZkRi9sc7G5tZ3mrJj9D+GQQFfeDW1
HLsLOPtfjAowhKJDUeUNGQZvnAgJbM442ike9jCzkNYWN4hYLsEOIdCDLRCDUK3CSEgaHoqqutEG
yiaJFBX6M4pDBR5gmqEjM7BYMAokdbJgxpRguIla5d1KEi/eQykK+gSr4p7HMiG18SGZYG63QA6X
EPIxXDEwuYlAeYDcxW85p9f0p5A+YwbBLhdswywJAXwTkOv1IFrSEUwbFIqvZQzhLq78Jqe3+8Gj
juUidm+4vAWjz27Bhzp4/50EiaCJFkziqFkGZX0OVgGj5RajqMNMdAKr3QIxRCA1iZmYxAKJDWFR
HuNjdwAl3GOyGuAH/CtLvkAkVQJEAOyQtcclaShVTc6Fj05KHyYAZ9xigfonfqcgo1mewFxChtiY
yzaAgxxfskaJEA9tw+WQMKHDYljOFuSuP4XJBASLWZ5pMFhfFCgMS5GY8slCAUFsrEnp0uI672ln
B57mARFGwmaYPjSeQv6S5OJDZQU/mMDnWxCLD2GiWFGrH5jJyWinCfCRoHegzGCdKRHZJsKGrOtQ
tKC4rCDacO//OflYJP0F8ZgWn0U8JPOU1jfRqqTHYJMMXAqzn/AKanDNgqRet7+rqYKiL0goI6Ev
SlzQpZhsqCv9rWdetEcboxFt7GW1p1EkT6B7i8FDQW4YHb4mVi1OqIRCCvLo63qYQykXcYD3VZ6s
wxGu8BZDCCY5Gt5ZHoxsmxIXRJgKF3OhJLEgrVrGem7JAEhSpLJic6dbfFBg816CDNc7muspzyag
/7abhKGu9NDD7pUqmROSYuYwMwd8N+JxTlnXpgIKkhxsYXOriAkNYzDWoOMqPdNK2KPKyjrsrU55
dAUWMUvy0CsJCSCCzGNWkY52y1KiHBgcdLuaR/binDxhKTaSrejZJVN+lkRFiMW55n7bjkqWToEJ
o7qmKdxjP9Y8LLndWR7fSi3vS7J6DIgERMqwA0FumC6Kt8g9M6hBpB7UxjIAy5kKF6Iq1Gwc5XBg
6DxN9LSm+jAJYLGkp9kY9Cpm2Bp4pkQE9TvYrua6aEbMQnijzN5/icqJY6FQF2X1BqYR6kw44Qq6
ByxEOJbFkADBnkxUIgfUtam5q4PRRJQ5kcLNCzt8FXfQ8bOFQtxbrN2zjBlzHy3bVgUpEFb2Bjqq
VLmW6nxMdJ4Od0aBei4ADU0d9gpaGRDvEZTDYLgno3dbMBcomED8mQeemumoTf5dom8T+iHbN4VB
VTJIEow1tMOOPfCnGQ/9bajzdRXjCbAzsxAsqe0viW2HLLOzhcuqk86+oPNhGcTDLe3YuLD5wEeH
gdkIMm3M9e9G8aioFKqyHYsgnERHS1izx2nbXNo1GXRfYpJPh6bo+IH1sNgwmQWrSrpdVJSS4thM
FJWmY1QBaaSqEyXblvSJoi22PXW1aPHIVFqLFn1brXUQRRGJdAMnummioca8kF1SuItbKWRhZkpb
TxmyCG5NTUsBDNH2BpKLT8NJHZR4DT9ETmzKlLU8CFMtU0M+Sqp78ebtzdmQUdSF/9wc+qsY+itC
RPuRqDoiz6xckleq+LimLRdaCYgkhleyIkpJQAlaDX5QANKrSSEYynRmQjPCNhbhJh0Zr6+Dixim
a+ExuisyOMHv8VSLbfTAUe5ZZYv14UbvvhtCuZ1NclopbCrIHG4QM3ZXxWek8NNSej1M/VqT1MdW
DS4GAuqCsHrCcKA/3aBxGzyWHc3BDGYia1hSMp1SW6K/m4RC1LUAthIm0jAzs6i2oRIHE5MzLfGY
uic9AvVu99YYSbaoFP8f0J+bYajJ/inLxkGxeza1qpHb7zXaK1okq/ols5xlIq8wI/B4URQAmkge
G8NFDRY0ejlWWv/NRjl08WVXkEGnCQ2tl0ROS0cuaK+g3jf4MJMY+RnIkJnhINpaaiS5HkdJHtu5
VZpyuNAvWgYqCrsxQIo/h2z361N5BlBPm4XGUU/orHfYv3c28R8L3aVPhMY2Efj1MkabU6h9lE+J
VW9ZWVlFJ5Uxv4N6BlUb4GaEwM42XZiNF5Pmy1qRROjToUqRcUyG8POQhiUSokAbo1/g6ixN3W2G
ux3gc4C2ENXnRNsKFe48QjeMKA1h7i75L+1cKwMFWijjin9hvCkXaC9dSr2Vq9V1Qf5/zb0gl9Y0
owduqKP4p6cal8bxUAhiuMe9wbZ+qbwikLn4uQbtpLh9URUYmvCqZy5o7ywTb1LLnAe0/fFbLnJh
9GvmU0QleFuCsobs4EnY0iTNQ4PN/Mas30DsxBTu2iA9JFrvgLbJjiRKEkUZQRpUGH4MtGciL24r
DpmumwuV4sfF8hTqSF1Ma4OkuKxrOIMLsOzjLLMgIt3Dyzm+uN8ugQTj0SQAy9dDzI6m3v4Y6jiP
OzX4gTOmobp8MUairdc0SWXeQLtu4/ZZHVLG1xo0naVB7CeVGcwS1D0t2bE2U6HGJPriJF5E2EGR
h0iQrywJxZbQ3GbVbSIYbI0zPp1CYjf7LuWOFsZp/Mzb7f3caHoQnbyPHvzoka6goeLimLf1BRY+
YDzmjGXIzA+6BZrFjnvIPuLPNiSrLWrBf6WyJtHOyew9Rgwx5U7ilKHEsBbAOlZXvrdsw9RTHRiw
2SkZqdwIbHqq7fAFWym96Qn3oSp6hUkIAilDCvu4B5Xf/uGvtMSJ2fDGaiuAJWhs2TZSuQTzKHcy
E/7wi5mYtzWnusGvCnuG26WRCBXV/NR3TvKMwjTufzJqBiSVE5TWKXSSW+gwCvT9SlfFYUcJGN2N
2r3qKgskasxcvvqpuAeXtMUfmD37apPffNlLfFEiRi3TSeoJZBLrq3gTFxQ2K8fidnDs8awC6C+M
Fh8JoycVyskQ/qflPT8I6aMg+GK3Pl72VVrenYHjlA8ABlg7lrc+y9q7XFDmLlJV3h2PLgknPraW
eBO3RJK6WUXYtfBNowr3X16AVIXvH0w8d7A36U4E9w/8Xe6Jgd8d+Ae7B2Lg7e54vnfQH7CXLTxw
k/rM0aADv0IpeBav0UL+FtIXBM0vtofnrb22J+5YG4/a+t297g78pOV33MHBwWQwmbg7XW9nwP0d
7u7s+p63O9mf7E32D/Z9sQd/tLxKbkUM0dlIDz9WGKT6nL5PJ6C/668n6keg4PcXS71Q1OCtbnen
1+vjI0Cj07fmNHhXf9VxNEOF0gkpSlE/V/Dh6rJcbe55X0p8Nm74jT2dRRhA5lmgLAhUfbeZ8LWS
SFTQNVQoSFpBORovlNjRn4Jsa/okxS9ZTZnoQ4sSsOB0ZlU88JuazR7DEz2/DaXoJy9R+B5xsVSk
bc7g+A+mjLcjSlkwZB/Fg+ufn7X+/PP/AJCgG+I=
===END CRASH DUMP===

**Comment by xZeroMCPE** [comment]
K , Working on it.

**Comment by Shock95** [comment]
Okie

**Comment by BobbyTowers** [comment]
[JgLhv4Zw.txt](https://github.com/AndreTheGamer/SurvivalGame/files/135402/JgLhv4Zw.txt)

**Comment by xZeroMCPE** [comment]
Working on it...

**Comment by xZeroMCPE** [comment]
Fixed :)
