### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by BobbyTowers** [AndreTheGamer/SurvivalGame#86]
[c0qSc9TM.txt](https://github.com/AndreTheGamer/SurvivalGame/files/141392/c0qSc9TM.txt)

**Comment by xZeroMCPE** [comment]
Hi, this released is still undergoing beta. As i stated there would be some issues but thanks for telling me. If you wan't a working release please visit the release page. :) 

Syntax Error is being fix now

**Comment by dries-c** [comment]
you use php7

**Comment by xZeroMCPE** [comment]
No, might i'm thinking of using it. But as of now its on php5

**Comment by Taki21** [comment]
Please note that PHP5 is compatible with PHP7
No need to change anything!

**Comment by Taki21** [comment]
However a great strategy would be:
`use pocketmine\event\player\{PlayerMoveEvent, PlayerDeathEvent};`
You can put all class names in the same folder!

**Comment by xZeroMCPE** [comment]
@Taki21 Ya
