### ISSUE TITLE
Please add timer or open pull request

### ISSUE THREAD

**Issue by Arkdevnoder** [AndreTheGamer/SurvivalGame#88]

**Comment by Arkdevnoder** [comment]
and please , remove support economy plugin. And add other classes. It is bad coding

**Comment by Arkdevnoder** [comment]
CallBackTask, it is so so laggy

**Comment by Arkdevnoder** [comment]
![screenshot_2016-03-07-21-12-30](https://cloud.githubusercontent.com/assets/14966273/13575197/5b1179a4-e4a9-11e5-93d9-bc792525cf6b.png)

**Comment by xZeroMCPE** [comment]
@darkspive  Please use the stable release via the release page. Instead of running it from source. And its being fix and ecnomy support will be removed :)

**Comment by MacHupTR** [comment]
@AndreTheGamer #
![screenshot_2016-03-07-20-55-28-1](https://cloud.githubusercontent.com/assets/16403705/13579612/1a32a978-e4a7-11e5-8b83-04186a70eb11.png)

Help me Pls fix Eror

**Comment by xZeroMCPE** [comment]
@MacHupTR Don't run the plugin from source because new features is being added on it and it will most likely contain some errors. Download the stable release by clicking [here](https://github.com/AndreTheGamer/SurvivalGame/releases/download/1.0.10/SurvivalGame_v1.0.10.phar)

**Comment by ghost** [comment]
@darkspive Economy has been removed
