### ISSUE TITLE
What are those???

### ISSUE THREAD

**Issue by ClockProgramming** [AndreTheGamer/SurvivalGame#99]
This plugin is completely broken. I just went to check out the Src code for the plugin and lots of error happened.

[y] Completely useless
[y] Incorrect Formatting 
[y] Uses github editor
[y] Missing codes
[y] Incorrect use of variables
[y] Etc

![image](https://cloud.githubusercontent.com/assets/16515013/17646803/03623898-620c-11e6-9e68-99678fe21f68.png)

You may contact me if you want to rewrite all of this.

**Comment by ClockProgramming** [comment]
See that red on the right scroll? It shows how many errors you did.

**Comment by xZeroMCPE** [comment]
Formating looks alright for me, and i don't use GitHub editor.. I use  netbeans .... I think it depends on what software you are using on which messed up the formating(S). But again if you are willing to help re-write it. Go head.

**Comment by ClockProgramming** [comment]
![image](https://cloud.githubusercontent.com/assets/16515013/17647514/16097f46-6226-11e6-8403-41f4349ac367.png)
Supposedly to be an comment right? it must have slash before *
\

**Comment by ClockProgramming** [comment]
I can rewrite the plugin when I have time

**Comment by xZeroMCPE** [comment]
No lol, i wasn't trying to make it a comment..... I know how to make multi line comments.

**Comment by xZeroMCPE** [comment]
Sure, rewrite it if you don't mind. Otherwise let it be!
